import { PRODUCT_CONFIG } from "@mewvis/product-config";
import { build } from "esbuild";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export async function buildDocsUi() {
  await build({
    entryPoints: [resolve(root, "ui/main.js")],
    outfile: resolve(root, PRODUCT_CONFIG.files.appUiScript),
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2022",
    minify: true,
    banner: { js: "// Generated by scripts/build-ui.mjs; edit ui/main.js instead." },
  });
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
)
  await buildDocsUi();
