# @generated by protocol/scripts/generate-bindings.mjs
# Sources: protocol/v1/schema/*.schema.json and protocol/v1/openrpc.json
# Do not edit this file directly.
from dataclasses import dataclass
from typing import Any
from enum import Enum


@dataclass
class Error:
    code: int
    message: str
    data: Any


class Jsonrpc(Enum):
    THE_20 = "2.0"


class RuntimePingRequest(Enum):
    AGENT_APPROVAL_ANSWER = "agent/approval/answer"
    AGENT_CHAT = "agent/chat"
    AGENT_QUESTION_ANSWER = "agent/question/answer"
    AGENT_RUN = "agent/run"
    AGENT_TOOLS_LIST = "agent/tools/list"
    COLLABORATION_MODES_LIST = "collaboration/modes/list"
    COLLABORATION_RUN = "collaboration/run"
    COLLABORATION_RUN_MODE = "collaboration/runMode"
    COLLABORATION_TIMELINE_READ = "collaboration/timeline/read"
    EXTENSIONS_COMMANDS_EXECUTE = "extensions/commands/execute"
    EXTENSIONS_COMMANDS_LIST = "extensions/commands/list"
    RUNTIME_EVENT = "runtime/event"
    RUNTIME_MODELS_LIST = "runtime/models/list"
    RUNTIME_PING = "runtime/ping"
    RUNTIME_RESULT = "runtime/result"
    RUNTIME_SESSIONS_LIST = "runtime/sessions/list"
    RUNTIME_SESSION_DEBUG_READ = "runtime/session/debug/read"
    RUNTIME_SESSION_READ = "runtime/session/read"
    RUNTIME_SHUTDOWN = "runtime/shutdown"
    SESSION_AGENT_COMPACT = "session/agent/compact"
    SESSION_AGENT_REBUILD = "session/agent/rebuild"
    SESSION_AGENT_SUMMARIZE = "session/agent/summarize"
    SESSION_MESSAGE_APPEND = "session/message/append"
    SESSION_MESSAGE_DELETE = "session/message/delete"
    SESSION_MESSAGE_EDIT = "session/message/edit"
    SESSION_READ = "session/read"
    SESSION_REBUILD = "session/rebuild"
    SESSION_SUMMARIZE = "session/summarize"


class AgentAccessBase(Enum):
    HOME = "home"
    TEMP = "temp"
    WORKSPACE = "workspace"


@dataclass
class AgentAccessPath:
    base: AgentAccessBase
    path: str | None
    """Optional relative path within the host-resolved base. Absolute paths, parent traversal
    and globs are forbidden.
    """


class AgentAccessPathsEnum(Enum):
    ALL = "all"


@dataclass
class AgentFilesystemAccess:
    read: list[AgentAccessPath] | AgentAccessPathsEnum | None
    write: list[AgentAccessPath] | AgentAccessPathsEnum | None
    """Allows creating, modifying and deleting files within the declared paths."""


@dataclass
class AgentNetworkAccess:
    hosts: list[str] | AgentAccessPathsEnum | None


@dataclass
class AgentProcessAccess:
    execute: bool | None


@dataclass
class AgentAccess:
    """Host-supplied hard access ceiling, independent of approval mode. Omitted capabilities are
    denied.
    """
    filesystem: AgentFilesystemAccess | None
    network: AgentNetworkAccess | None
    process: AgentProcessAccess | None


class AgentRuntimeApplicationKind(Enum):
    DSH = "dsh"
    MEWVIS = "mewvis"


@dataclass
class AgentRuntimeApplication:
    entry: str
    id: str
    kind: AgentRuntimeApplicationKind
    package_root: str
    config: dict[str, Any] | None
    patch_path: str | None


@dataclass
class AgentRuntimeApplicationResources:
    items: list[AgentRuntimeApplication] | None
    settings_path: str | None


@dataclass
class AgentRuntimeMCPResources:
    servers: list[Any] | None


@dataclass
class AgentRuntimeSkillResources:
    bundled_path: list[str] | str | None
    enabled: list[str] | None
    paths: list[str] | None


@dataclass
class AgentRuntimeToolResources:
    allowed: list[str] | None


@dataclass
class AgentRuntimeResources:
    applications: AgentRuntimeApplicationResources | None
    mcp: AgentRuntimeMCPResources | None
    skills: AgentRuntimeSkillResources | None
    tools: AgentRuntimeToolResources | None


class RuntimeAPIFormat(Enum):
    ANTHROPIC_MESSAGES = "anthropic-messages"
    AZURE_OPENAI_RESPONSES = "azure-openai-responses"
    GOOGLE_GENERATIVE_AI = "google-generative-ai"
    OPENAI_CODEX_RESPONSES = "openai-codex-responses"
    OPENAI_COMPLETIONS = "openai-completions"
    OPENAI_RESPONSES = "openai-responses"
    OPENROUTER = "openrouter"


@dataclass
class RuntimeModelCost:
    cache_read: float
    cache_write: float
    input: float
    output: float


class RuntimeModelInputModality(Enum):
    IMAGE = "image"
    TEXT = "text"


@dataclass
class RuntimeModelInput:
    api_format: RuntimeAPIFormat
    catalog_model_id: str
    model_id: str
    provider: str
    api_endpoint: str | None
    api_key: str | None
    context_window: float | None
    cost: RuntimeModelCost | None
    headers: dict[str, str] | None
    input: list[RuntimeModelInputModality] | None
    max_tokens: float | None
    reasoning: bool | None
    thinking_level: str | None


@dataclass
class CollaborationAgent:
    id: str
    label: str
    allowed_tools: list[str] | None
    enabled_skills: list[str] | None
    resources: AgentRuntimeResources | None
    runtime_model: RuntimeModelInput | None
    system_prompt: str | None


@dataclass
class RuntimeModelCatalogAPI:
    api_format: RuntimeAPIFormat
    api_endpoint: str | None


@dataclass
class RuntimeThinkingOption:
    label: str
    value: str


@dataclass
class RuntimeModelThinking:
    levels: list[RuntimeThinkingOption]
    default_level: str | None


@dataclass
class RuntimeModelSummary:
    context_window: float
    cost: RuntimeModelCost
    id: str
    input: list[RuntimeModelInputModality]
    max_tokens: float
    name: str
    reasoning: bool
    headers: dict[str, str] | None
    thinking: dict[str, RuntimeModelThinking] | None


@dataclass
class RuntimeModelProviderSummary:
    apis: list[RuntimeModelCatalogAPI]
    models: dict[str, RuntimeModelSummary]
    website_url: str


class InputMode(Enum):
    TEXT = "text"


@dataclass
class Command:
    description: str
    id: str
    parameters: dict[str, Any]
    input_mode: InputMode | None
    label: str | None


@dataclass
class RuntimeDisplaySummary:
    generated_at: float
    record_id: str
    summary: str
    target_leaf_id: str
    timestamp: float
    chunk_count: float | None
    entry_count: float | None
    llm_call_count: float | None
    message_count: float | None
    model_id: str | None
    runtime_id: str | None
    source_char_count: float | None
    summary_instruction: str | None


@dataclass
class RuntimeSessionRef:
    session_root_dir: str
    assistant_message_record_id: str | None
    request_context_record_id: str | None
    runtime_instruction_record_id: str | None
    user_message_record_id: str | None


class SubtaskOutputEventType(Enum):
    DONE = "done"
    ERROR = "error"
    REPLACE_TEXT = "replace_text"
    STARTED = "started"
    TEXT_DELTA = "text_delta"
    THINKING_DELTA = "thinking_delta"
    THINKING_END = "thinking_end"
    TOOL_CALL_DELTA = "tool_call_delta"
    TOOL_CALL_END = "tool_call_end"
    TOOL_CALL_START = "tool_call_start"
    TOOL_EXECUTION_END = "tool_execution_end"
    TOOL_EXECUTION_START = "tool_execution_start"
    TOOL_EXECUTION_UPDATE = "tool_execution_update"


@dataclass
class SubtaskOutputEvent:
    type: SubtaskOutputEventType
    args: Any
    content: str | None
    delta: str | None
    is_error: bool | None
    message: str | None
    partial_result: Any
    result: Any
    runtime_session: RuntimeSessionRef | None
    task_id: str | None
    text: str | None
    tool_call_id: str | None
    tool_name: str | None


@dataclass
class AskUserOption:
    label: str
    value: str
    description: str | None


class InputType(Enum):
    SELECT = "select"
    TEXT = "text"


@dataclass
class AskUserInput:
    type: InputType
    label: str | None
    options: list[AskUserOption] | None
    selected: str | None


class State(Enum):
    CANCELLED = "cancelled"
    COMPLETED = "completed"
    FAILED = "failed"
    PAUSED = "paused"
    PAUSING = "pausing"
    RUNNING = "running"


class EventType(Enum):
    APPROVAL_REQUESTED = "approval_requested"
    APPROVAL_RESOLVED = "approval_resolved"
    DONE = "done"
    ERROR = "error"
    EXTENSION_ACTIVITY = "extension_activity"
    QUESTION = "question"
    QUESTION_ANSWERED = "question_answered"
    REPLACE_TEXT = "replace_text"
    STARTED = "started"
    SUBTASK_EVENT = "subtask_event"
    TEXT_DELTA = "text_delta"
    THINKING_DELTA = "thinking_delta"
    THINKING_END = "thinking_end"
    TOOL_CALL_DELTA = "tool_call_delta"
    TOOL_CALL_END = "tool_call_end"
    TOOL_CALL_START = "tool_call_start"
    TOOL_EXECUTION_END = "tool_execution_end"
    TOOL_EXECUTION_START = "tool_execution_start"
    TOOL_EXECUTION_UPDATE = "tool_execution_update"


@dataclass
class Event:
    type: EventType
    activity_id: str | None
    answer: str | None
    """The user's answer, or null when the user cancels answering."""

    approval_id: str | None
    approved: bool | None
    args: Any
    avatar: str | None
    content: str | None
    context: str | None
    delta: str | None
    details: str | None
    event: SubtaskOutputEvent | None
    execution_id: str | None
    expires_at: float | int | None
    """Unix timestamp in milliseconds when this question expires."""

    extension_id: str | None
    input: AskUserInput | None
    is_error: bool | None
    message: str | None
    partial_result: Any
    pausable: bool | None
    question: str | None
    question_id: str | None
    reason: str | None
    result: Any
    revision: int | None
    runtime_session: RuntimeSessionRef | None
    state: State | None
    subtask_id: str | None
    summary: str | None
    task_id: str | None
    text: str | None
    title: str | None
    tool_call_id: str | None
    tool_name: str | None


class Source(Enum):
    AGENT = "agent"
    COLLABORATION = "collaboration"
    RUNTIME = "runtime"


class EventStatus(Enum):
    DONE = "done"
    ERROR = "error"
    SKIPPED = "skipped"
    STARTED = "started"


@dataclass
class RuntimeTimelineItem:
    id: str
    index: int
    source: Source
    type: str
    agent_role_id: str | None
    agent_task_id: str | None
    detail: str | None
    mode_id: str | None
    status: EventStatus | None
    step_id: str | None
    step_type: str | None
    task_id: str | None
    timestamp: str | None
    workflow_id: str | None
    workflow_run_id: str | None


@dataclass
class Ledger:
    entries: list[Any]
    header: Any


@dataclass
class Message:
    content: str
    role: str
    message_record_id: str | None
    metadata: dict[str, Any] | None
    timestamp: float | None


@dataclass
class CollaborationMode:
    id: str
    label: str
    version: str


@dataclass
class CollaborationParticipant:
    id: str
    kind: str


class AgentPermissionMode(Enum):
    ASK = "ask"
    AUTO = "auto"
    FULL = "full"


@dataclass
class AgentPermissionOption:
    description: str
    is_default: bool
    label: str
    mode: AgentPermissionMode


@dataclass
class AgentPermissions:
    mode: AgentPermissionMode


@dataclass
class RuntimeSessionAuxiliaryEntry:
    content: str
    record_id: str
    timestamp: float
    metadata: dict[str, Any] | None


class RuntimeLinkStatus(Enum):
    DONE = "done"
    ERROR = "error"
    RUNNING = "running"


@dataclass
class RuntimeLink:
    assistant_message_record_ids: list[str]
    link_id: str
    message_record_ids: list[str]
    request_context_record_ids: list[str]
    runtime_instruction_record_ids: list[str]
    agent_role_id: str | None
    agent_session_id: str | None
    ended_at: float | None
    parent_entry_id: str | None
    root_user_entry_id: str | None
    run_id: str | None
    runtime: str | None
    runtime_id: str | None
    started_at: float | None
    status: RuntimeLinkStatus | None
    stream_id: str | None
    system_message_record_id: str | None
    task_id: str | None
    turn_id: str | None
    user_message_record_id: str | None


@dataclass
class RuntimeSessionSummary:
    entry_count: int
    mode_ids: list[str]
    session_root_dir: str
    trace_count: int
    workflow_ids: list[str]
    workflow_run_ids: list[str]
    workspace_path: str
    created_at: str | None
    latest_workflow_run_id: str | None
    leaf_id: str | None
    session_id: str | None
    updated_at: str | None


@dataclass
class CollaborationSkippedStep:
    reason: str
    step_id: str
    condition: dict[str, Any] | None


class StepTypeEnum(Enum):
    AGENT = "agent"
    CONDITION = "condition"
    DISPATCH = "dispatch"
    ROUTER = "router"
    TRANSFORM = "transform"


@dataclass
class CollaborationS:
    step_id: str
    agent_role_id: str | None
    agent_task_id: str | None
    condition: dict[str, Any] | None
    output: Any
    output_key: str | None
    reason: str | None
    route: str | None
    step_type: StepTypeEnum | None
    text: str | None


@dataclass
class CollaborationStepResult:
    output_key: str
    step_id: str
    step_type: StepTypeEnum
    text: str
    agent_role_id: str | None
    agent_task_id: str | None
    output: Any
    route: str | None


class Scope(Enum):
    AGENT = "agent"


@dataclass
class AgentTarget:
    agent_role_id: str
    scope: Scope


@dataclass
class AgentTool:
    enabled_by_default: bool
    label: str
    name: str
    description: str | None


class PurpleType(Enum):
    ACK = "ack"
    AGENT_EVENT = "agent_event"
    AGENT_TOOLS = "agent_tools"
    APPROVAL_REQUESTED = "approval_requested"
    APPROVAL_RESOLVED = "approval_resolved"
    CHAT_RESULT = "chat_result"
    COLLABORATION_MODES_RESULT = "collaboration_modes_result"
    COLLABORATION_RESULT = "collaboration_result"
    COLLABORATION_TIMELINE_RESULT = "collaboration_timeline_result"
    DONE = "done"
    ERROR = "error"
    EXTENSION_ACTIVITY = "extension_activity"
    EXTENSION_COMMANDS_RESULT = "extension_commands_result"
    EXTENSION_COMMAND_RESULT = "extension_command_result"
    PONG = "pong"
    QUESTION = "question"
    QUESTION_ANSWERED = "question_answered"
    REPLACE_TEXT = "replace_text"
    RUNTIME_MODELS = "runtime_models"
    RUNTIME_SESSIONS_RESULT = "runtime_sessions_result"
    RUNTIME_SESSION_DEBUG_RESULT = "runtime_session_debug_result"
    RUNTIME_SESSION_RESULT = "runtime_session_result"
    SESSION_MUTATION_RESULT = "session_mutation_result"
    SESSION_RESULT = "session_result"
    SHUTDOWN_ACK = "shutdown_ack"
    STARTED = "started"
    STEP_DONE = "step_done"
    STEP_SKIPPED = "step_skipped"
    STEP_STARTED = "step_started"
    SUBTASK_EVENT = "subtask_event"
    TASK_RESULT = "task_result"
    TEXT_DELTA = "text_delta"
    THINKING_DELTA = "thinking_delta"
    THINKING_END = "thinking_end"
    TOOL_CALL_DELTA = "tool_call_delta"
    TOOL_CALL_END = "tool_call_end"
    TOOL_CALL_START = "tool_call_start"
    TOOL_EXECUTION_END = "tool_execution_end"
    TOOL_EXECUTION_START = "tool_execution_start"
    TOOL_EXECUTION_UPDATE = "tool_execution_update"
    WORKFLOW_DONE = "workflow_done"
    WORKFLOW_STARTED = "workflow_started"


class ExecutionMode(Enum):
    PARALLEL = "parallel"
    SERIAL = "serial"


@dataclass
class WorkflowStep:
    id: str
    type: StepTypeEnum


@dataclass
class Workflow:
    id: str
    execution_mode: ExecutionMode | None
    label: str | None
    max_steps: int | None
    metadata: dict[str, Any] | None
    steps: list[WorkflowStep] | None
    version: str | None


@dataclass
class AgentRuntimeEvent:
    activity_id: str | None
    agent_access: AgentAccess | None
    agent_role_id: str | None
    agent_task_id: str | None
    agents: list[CollaborationAgent] | None
    answer: str | None
    """The user's answer, or null when the user cancels answering."""

    approval_id: str | None
    approved: bool | None
    args: Any
    arguments: dict[str, Any] | None
    avatar: str | None
    bootstrap_instruction: str | None
    catalog: dict[str, RuntimeModelProviderSummary] | None
    command_id: str | None
    commands: list[Command] | None
    compacted: bool | None
    content: str | None
    context: Any
    default_tool_names: list[str] | None
    delta: str | None
    details: str | None
    display_summaries: list[RuntimeDisplaySummary] | None
    display_summary: RuntimeDisplaySummary | None
    event: Event | None
    events: list[RuntimeTimelineItem] | None
    execution_id: str | None
    expires_at: float | int | None
    """Unix timestamp in milliseconds when this question expires."""

    extension_id: str | None
    include_ledger: bool | None
    include_timeline: bool | None
    include_trace: bool | None
    input: Any
    is_error: bool | None
    ledger: Ledger | None
    limit: int | None
    max_depth: int | None
    message: str | None
    message_record_id: str | None
    message_record_ids: list[str] | None
    messages: list[Message] | None
    mode: str | None
    modes: list[CollaborationMode] | None
    options: dict[str, Any] | None
    output: Any
    partial_result: Any
    participants: list[CollaborationParticipant] | None
    pausable: bool | None
    permission_options: list[AgentPermissionOption] | None
    permissions: AgentPermissions | None
    question: str | None
    question_id: str | None
    reason: str | None
    rebuilt: bool | None
    record_user_message: bool | None
    request_context: str | None
    request_contexts: list[RuntimeSessionAuxiliaryEntry] | None
    request_id: str | None
    resources: AgentRuntimeResources | None
    result: Any
    revision: int | None
    root_dir: str | None
    rpc_request_id: int | str | None
    runtime: dict[str, Any] | None
    runtime_instruction: str | None
    runtime_instructions: list[RuntimeSessionAuxiliaryEntry] | None
    runtime_links: list[RuntimeLink] | None
    runtime_model: RuntimeModelInput | None
    runtime_session: RuntimeSessionRef | None
    session: RuntimeSessionSummary | None
    session_root_dir: str | None
    sessions: list[RuntimeSessionSummary] | None
    skipped_steps: list[CollaborationSkippedStep] | None
    state: State | None
    step: CollaborationS | None
    step_id: str | None
    step_type: StepTypeEnum | None
    steps: list[CollaborationStepResult] | None
    stream: bool | None
    stream_id: str | None
    subtask_id: str | None
    success: bool | None
    summary: str | None
    system_prompt: str | None
    target: AgentTarget | None
    task_id: str | None
    text: str | None
    thinking: str | None
    timeline: list[RuntimeTimelineItem] | None
    timeline_limit: int | None
    title: str | None
    tool_call_id: str | None
    tool_name: str | None
    tools: list[AgentTool] | None
    trace: list[Any] | None
    trace_limit: int | None
    type: PurpleType | None
    user_message: str | None
    value: Any
    workflow: Workflow | None
    workflow_id: str | None
    workflow_run_id: str | None
    workspace_path: str | None


@dataclass
class RuntimeSessionMessage:
    content: str
    message_record_id: str
    role: str
    timestamp: float
    metadata: dict[str, Any] | None


class AgentRuntimeResultType(Enum):
    ACK = "ack"
    AGENT_TOOLS = "agent_tools"
    CHAT_RESULT = "chat_result"
    COLLABORATION_MODES_RESULT = "collaboration_modes_result"
    COLLABORATION_RESULT = "collaboration_result"
    COLLABORATION_TIMELINE_RESULT = "collaboration_timeline_result"
    EXTENSION_COMMANDS_RESULT = "extension_commands_result"
    EXTENSION_COMMAND_RESULT = "extension_command_result"
    PONG = "pong"
    RUNTIME_MODELS = "runtime_models"
    RUNTIME_SESSIONS_RESULT = "runtime_sessions_result"
    RUNTIME_SESSION_DEBUG_RESULT = "runtime_session_debug_result"
    RUNTIME_SESSION_RESULT = "runtime_session_result"
    SESSION_MUTATION_RESULT = "session_mutation_result"
    SESSION_RESULT = "session_result"
    SHUTDOWN_ACK = "shutdown_ack"
    TASK_RESULT = "task_result"


@dataclass
class AgentRuntimeResult:
    type: AgentRuntimeResultType
    catalog: dict[str, RuntimeModelProviderSummary] | None
    commands: list[Command] | None
    compacted: bool | None
    default_tool_names: list[str] | None
    display_summaries: list[RuntimeDisplaySummary] | None
    display_summary: RuntimeDisplaySummary | None
    events: list[RuntimeTimelineItem] | None
    ledger: Ledger | None
    message: str | None
    message_record_id: str | None
    message_record_ids: list[str] | None
    messages: list[RuntimeSessionMessage] | None
    mode: str | None
    modes: list[CollaborationMode] | None
    output: Any
    permission_options: list[AgentPermissionOption] | None
    rebuilt: bool | None
    request_contexts: list[RuntimeSessionAuxiliaryEntry] | None
    rpc_request_id: int | str | None
    runtime_instructions: list[RuntimeSessionAuxiliaryEntry] | None
    runtime_links: list[RuntimeLink] | None
    session: RuntimeSessionSummary | None
    session_root_dir: str | None
    sessions: list[RuntimeSessionSummary] | None
    skipped_steps: list[CollaborationSkippedStep] | None
    steps: list[CollaborationStepResult] | None
    success: bool | None
    summary: str | None
    task_id: str | None
    text: str | None
    thinking: str | None
    timeline: list[RuntimeTimelineItem] | None
    tools: list[AgentTool] | None
    trace: list[Any] | None
    value: Any
    workflow_run_id: str | None


@dataclass
class AgentRuntimeMessage:
    """Any JSON-RPC message crossing the agent runtime stdio boundary."""

    jsonrpc: Jsonrpc
    error: Error | None
    id: int | str | None
    method: RuntimePingRequest | None
    params: AgentRuntimeEvent | None
    result: AgentRuntimeResult | None

from typing import Final

AGENT_RUNTIME_PROTOCOL_VERSION: Final[str] = "1.0.0"
AGENT_RUNTIME_JSON_RPC_METHODS: Final[tuple[str, ...]] = ("runtime/ping", "runtime/shutdown", "agent/tools/list", "runtime/models/list", "agent/chat", "agent/run", "agent/question/answer", "session/read", "session/agent/compact", "session/agent/rebuild", "session/summarize", "session/agent/summarize", "session/message/edit", "session/message/delete", "session/message/append", "session/rebuild", "runtime/sessions/list", "runtime/session/read", "runtime/session/debug/read", "collaboration/timeline/read", "collaboration/modes/list", "collaboration/run", "collaboration/runMode", "agent/approval/answer", "extensions/commands/list", "extensions/commands/execute",)
AGENT_RUNTIME_NOTIFICATION_METHODS: Final[tuple[str, ...]] = ("runtime/event", "runtime/result",)
AGENT_RUNTIME_EVENT_TYPES: Final[tuple[str, ...]] = ("subtask_event", "extension_activity", "started", "question", "question_answered", "replace_text", "text_delta", "thinking_delta", "thinking_end", "tool_call_start", "tool_call_delta", "tool_call_end", "tool_execution_start", "tool_execution_update", "tool_execution_end", "done", "error", "workflow_started", "step_started", "agent_event", "step_done", "step_skipped", "workflow_done", "approval_requested", "approval_resolved",)
AGENT_RUNTIME_RESULT_TYPES: Final[tuple[str, ...]] = ("ack", "agent_tools", "chat_result", "pong", "shutdown_ack", "task_result", "runtime_models", "session_result", "session_mutation_result", "collaboration_result", "collaboration_modes_result", "runtime_sessions_result", "runtime_session_result", "runtime_session_debug_result", "collaboration_timeline_result", "extension_commands_result", "extension_command_result",)
EVENT_SUBTASK_EVENT: Final[str] = "subtask_event"
EVENT_EXTENSION_ACTIVITY: Final[str] = "extension_activity"
EVENT_STARTED: Final[str] = "started"
EVENT_QUESTION: Final[str] = "question"
EVENT_QUESTION_ANSWERED: Final[str] = "question_answered"
EVENT_REPLACE_TEXT: Final[str] = "replace_text"
EVENT_TEXT_DELTA: Final[str] = "text_delta"
EVENT_THINKING_DELTA: Final[str] = "thinking_delta"
EVENT_THINKING_END: Final[str] = "thinking_end"
EVENT_TOOL_CALL_START: Final[str] = "tool_call_start"
EVENT_TOOL_CALL_DELTA: Final[str] = "tool_call_delta"
EVENT_TOOL_CALL_END: Final[str] = "tool_call_end"
EVENT_TOOL_EXECUTION_START: Final[str] = "tool_execution_start"
EVENT_TOOL_EXECUTION_UPDATE: Final[str] = "tool_execution_update"
EVENT_TOOL_EXECUTION_END: Final[str] = "tool_execution_end"
EVENT_DONE: Final[str] = "done"
EVENT_ERROR: Final[str] = "error"
EVENT_WORKFLOW_STARTED: Final[str] = "workflow_started"
EVENT_STEP_STARTED: Final[str] = "step_started"
EVENT_AGENT_EVENT: Final[str] = "agent_event"
EVENT_STEP_DONE: Final[str] = "step_done"
EVENT_STEP_SKIPPED: Final[str] = "step_skipped"
EVENT_WORKFLOW_DONE: Final[str] = "workflow_done"
EVENT_APPROVAL_REQUESTED: Final[str] = "approval_requested"
EVENT_APPROVAL_RESOLVED: Final[str] = "approval_resolved"
RESULT_ACK: Final[str] = "ack"
RESULT_AGENT_TOOLS: Final[str] = "agent_tools"
RESULT_CHAT_RESULT: Final[str] = "chat_result"
RESULT_PONG: Final[str] = "pong"
RESULT_SHUTDOWN_ACK: Final[str] = "shutdown_ack"
RESULT_TASK_RESULT: Final[str] = "task_result"
RESULT_RUNTIME_MODELS: Final[str] = "runtime_models"
RESULT_SESSION_RESULT: Final[str] = "session_result"
RESULT_SESSION_MUTATION_RESULT: Final[str] = "session_mutation_result"
RESULT_COLLABORATION_RESULT: Final[str] = "collaboration_result"
RESULT_COLLABORATION_MODES_RESULT: Final[str] = "collaboration_modes_result"
RESULT_RUNTIME_SESSIONS_RESULT: Final[str] = "runtime_sessions_result"
RESULT_RUNTIME_SESSION_RESULT: Final[str] = "runtime_session_result"
RESULT_RUNTIME_SESSION_DEBUG_RESULT: Final[str] = "runtime_session_debug_result"
RESULT_COLLABORATION_TIMELINE_RESULT: Final[str] = "collaboration_timeline_result"
RESULT_EXTENSION_COMMANDS_RESULT: Final[str] = "extension_commands_result"
RESULT_EXTENSION_COMMAND_RESULT: Final[str] = "extension_command_result"
