mod commands;
pub mod db;
mod product_config;
mod services;

use commands::{
    agent_runtime::{
        abort_agent_runtime_agent, answer_agent_runtime_question,
        append_agent_runtime_session_messages, compact_agent_runtime_session,
        create_agent_runtime_session, delete_agent_runtime_session,
        delete_agent_runtime_session_message, dispose_agent_runtime_session_workers,
        edit_agent_runtime_session_message, get_agent_runtime_collaboration_timeline,
        get_agent_runtime_session, get_agent_runtime_session_debug, list_agent_runtime_sessions,
        list_agent_runtime_tools, read_agent_runtime_session, rebuild_agent_runtime_agent_session,
        rebuild_agent_runtime_session, run_agent_runtime_agent, run_agent_runtime_chat,
        run_agent_runtime_collaboration, run_agent_runtime_collaboration_mode,
        summarize_agent_runtime_session, AgentRuntimeSupervisor,
    },
    app::{
        get_config_database_status, initialize_config_database, rebuild_config_database,
        rebuild_workspace_database, AppStartupState,
    },
    settings::{
        delete_ai_agent, delete_collaboration_workflow, delete_knowledge_collection,
        delete_knowledge_source, get_ai_agent_settings, get_knowledge_index_status,
        get_knowledge_settings, get_llm_settings, import_knowledge_files, list_embedding_profiles,
        list_knowledge_library, rebuild_knowledge_index, save_ai_agent,
        save_collaboration_workflow, save_embedding_profile, save_knowledge_collection,
        save_knowledge_settings, save_knowledge_source, save_llm_settings,
        set_knowledge_collection_sources,
    },
    workspace::{
        cleanup_orphan_agent_sessions, clear_tavern_state, create_story_record, create_workspace,
        create_workspace_version, create_workspace_version_branch, delete_chat,
        delete_story_record, delete_workspace, delete_workspace_file,
        discard_workspace_version_file_changes, get_agent_session_status, get_workspace_overview,
        get_workspace_skills, get_workspace_version_commit_file_diff,
        get_workspace_version_control_status, get_workspace_version_file_diff, import_story_record,
        initialize_workspace_version_control, install_skill_from_marketplace, list_chats,
        list_story_records, list_workspace_files, list_workspace_version_files,
        list_workspace_versions, load_chat, load_tavern_state, read_workspace_file,
        read_workspace_file_optional, read_workspace_version_file, remove_app_skill,
        reset_agent_sessions_for_chat, restore_workspace_version, save_chat, save_tavern_state,
        save_workspace_skills, search_skill_marketplace, search_workspace_knowledge,
        set_chat_unread, switch_workspace_version_branch, unwatch_workspace_files,
        update_story_record, update_workspace, watch_workspace_files, write_workspace_file,
        write_workspace_files_atomic, WorkspaceFileWatchers,
    },
};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .manage(AgentRuntimeSupervisor::default())
        .manage(AppStartupState::default())
        .manage(WorkspaceFileWatchers::default())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_sql::Builder::default().build())
        .invoke_handler(tauri::generate_handler![
            initialize_config_database,
            get_config_database_status,
            rebuild_config_database,
            rebuild_workspace_database,
            get_workspace_overview,
            create_workspace,
            update_workspace,
            delete_workspace,
            get_llm_settings,
            save_llm_settings,
            get_ai_agent_settings,
            save_ai_agent,
            delete_ai_agent,
            save_collaboration_workflow,
            delete_collaboration_workflow,
            list_knowledge_library,
            get_knowledge_settings,
            save_knowledge_settings,
            list_embedding_profiles,
            save_embedding_profile,
            save_knowledge_collection,
            delete_knowledge_collection,
            save_knowledge_source,
            import_knowledge_files,
            delete_knowledge_source,
            set_knowledge_collection_sources,
            get_knowledge_index_status,
            rebuild_knowledge_index,
            list_agent_runtime_tools,
            run_agent_runtime_chat,
            run_agent_runtime_agent,
            run_agent_runtime_collaboration,
            run_agent_runtime_collaboration_mode,
            answer_agent_runtime_question,
            abort_agent_runtime_agent,
            create_agent_runtime_session,
            read_agent_runtime_session,
            list_agent_runtime_sessions,
            get_agent_runtime_session,
            get_agent_runtime_session_debug,
            get_agent_runtime_collaboration_timeline,
            dispose_agent_runtime_session_workers,
            delete_agent_runtime_session,
            append_agent_runtime_session_messages,
            rebuild_agent_runtime_session,
            rebuild_agent_runtime_agent_session,
            compact_agent_runtime_session,
            summarize_agent_runtime_session,
            edit_agent_runtime_session_message,
            delete_agent_runtime_session_message,
            get_workspace_skills,
            save_workspace_skills,
            search_skill_marketplace,
            install_skill_from_marketplace,
            remove_app_skill,
            search_workspace_knowledge,
            list_chats,
            load_chat,
            save_chat,
            set_chat_unread,
            delete_chat,
            list_story_records,
            create_story_record,
            import_story_record,
            update_story_record,
            delete_story_record,
            load_tavern_state,
            save_tavern_state,
            clear_tavern_state,
            get_agent_session_status,
            cleanup_orphan_agent_sessions,
            reset_agent_sessions_for_chat,
            watch_workspace_files,
            unwatch_workspace_files,
            list_workspace_files,
            read_workspace_file,
            read_workspace_file_optional,
            write_workspace_file,
            write_workspace_files_atomic,
            delete_workspace_file,
            get_workspace_version_control_status,
            initialize_workspace_version_control,
            get_workspace_version_file_diff,
            discard_workspace_version_file_changes,
            get_workspace_version_commit_file_diff,
            create_workspace_version,
            create_workspace_version_branch,
            switch_workspace_version_branch,
            list_workspace_versions,
            list_workspace_version_files,
            read_workspace_version_file,
            restore_workspace_version
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
