mod commands;
pub mod db;
mod product_config;
mod services;

use commands::{
    agent_runtime::{
        abort_agent_runtime_agent, answer_agent_runtime_question,
        append_agent_runtime_session_messages, compact_agent_runtime_session,
        create_agent_runtime_session, delete_agent_runtime_session,
        delete_agent_runtime_session_message, dispose_agent_runtime_session_workers,
        edit_agent_runtime_session_message, list_agent_runtime_agents, read_agent_runtime_session,
        rebuild_agent_runtime_agent_session, rebuild_agent_runtime_session,
        run_agent_runtime_agent, run_agent_runtime_chat, summarize_agent_runtime_session,
        AgentRuntimeSupervisor,
    },
    app::{
        get_config_database_status, initialize_config_database, rebuild_config_database,
        rebuild_workspace_database, AppStartupState,
    },
    settings::{
        delete_ai_agent, delete_collaboration_workflow, delete_knowledge_collection,
        delete_knowledge_source, get_ai_agent_settings, get_knowledge_index_status,
        get_knowledge_settings, get_llm_settings, import_knowledge_files, list_embedding_profiles,
        list_knowledge_library, rebuild_knowledge_index, save_ai_agent,
        save_collaboration_workflow, save_embedding_profile, save_knowledge_collection,
        save_knowledge_settings, save_knowledge_source, save_llm_settings,
        set_knowledge_collection_sources,
    },
    workspace::{
        cleanup_orphan_agent_sessions, create_workspace, create_workspace_version,
        create_workspace_version_branch, delete_chat_session, delete_workspace,
        delete_workspace_file, discard_workspace_version_file_changes, get_agent_session_status,
        get_workspace_overview, get_workspace_skills, get_workspace_version_commit_file_diff,
        get_workspace_version_control_status, get_workspace_version_file_diff,
        initialize_workspace_version_control, install_skill_from_marketplace, list_chat_sessions,
        list_workspace_files, list_workspace_version_files, list_workspace_versions,
        load_chat_session, load_story_state, load_tavern_state, read_workspace_file,
        read_workspace_version_file,
        remove_app_skill, reset_agent_sessions_for_chat, restore_workspace_version,
        save_chat_session, save_story_state, save_tavern_state, save_workspace_skills,
        search_skill_marketplace, search_workspace_knowledge, set_chat_session_unread,
        switch_workspace_version_branch, update_workspace, write_workspace_file,
    },
};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .manage(AgentRuntimeSupervisor::default())
        .manage(AppStartupState::default())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_sql::Builder::default().build())
        .invoke_handler(tauri::generate_handler![
            initialize_config_database,
            get_config_database_status,
            rebuild_config_database,
            rebuild_workspace_database,
            get_workspace_overview,
            create_workspace,
            update_workspace,
            delete_workspace,
            get_llm_settings,
            save_llm_settings,
            get_ai_agent_settings,
            save_ai_agent,
            delete_ai_agent,
            save_collaboration_workflow,
            delete_collaboration_workflow,
            list_knowledge_library,
            get_knowledge_settings,
            save_knowledge_settings,
            list_embedding_profiles,
            save_embedding_profile,
            save_knowledge_collection,
            delete_knowledge_collection,
            save_knowledge_source,
            import_knowledge_files,
            delete_knowledge_source,
            set_knowledge_collection_sources,
            get_knowledge_index_status,
            rebuild_knowledge_index,
            list_agent_runtime_agents,
            run_agent_runtime_chat,
            run_agent_runtime_agent,
            answer_agent_runtime_question,
            abort_agent_runtime_agent,
            create_agent_runtime_session,
            read_agent_runtime_session,
            dispose_agent_runtime_session_workers,
            delete_agent_runtime_session,
            append_agent_runtime_session_messages,
            rebuild_agent_runtime_session,
            rebuild_agent_runtime_agent_session,
            compact_agent_runtime_session,
            summarize_agent_runtime_session,
            edit_agent_runtime_session_message,
            delete_agent_runtime_session_message,
            get_workspace_skills,
            save_workspace_skills,
            search_skill_marketplace,
            install_skill_from_marketplace,
            remove_app_skill,
            search_workspace_knowledge,
            list_chat_sessions,
            load_chat_session,
            save_chat_session,
            set_chat_session_unread,
            delete_chat_session,
            load_story_state,
            save_story_state,
            load_tavern_state,
            save_tavern_state,
            get_agent_session_status,
            cleanup_orphan_agent_sessions,
            reset_agent_sessions_for_chat,
            list_workspace_files,
            read_workspace_file,
            write_workspace_file,
            delete_workspace_file,
            get_workspace_version_control_status,
            initialize_workspace_version_control,
            get_workspace_version_file_diff,
            discard_workspace_version_file_changes,
            get_workspace_version_commit_file_diff,
            create_workspace_version,
            create_workspace_version_branch,
            switch_workspace_version_branch,
            list_workspace_versions,
            list_workspace_version_files,
            read_workspace_version_file,
            restore_workspace_version
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
