// Generated by pnpm sync-product-config. Do not edit.
pub const SERVER_RESOURCES: &str = "MEWVIS_SERVER_RESOURCES";
pub const SERVER_PORT: &str = "MEWVIS_SERVER_PORT";
pub const SERVER_TOKEN: &str = "MEWVIS_SERVER_TOKEN";
pub const DESKTOP_DEV_ORIGIN: &str = "MEWVIS_DESKTOP_DEV_ORIGIN";
