import { writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const targetPath = join(__dirname, "..", "agent-bridge", "src", "llm", "data.ts");
const MODELS_DEV_URL = "https://models.dev/api.json";
const RAW_CATALOG_EXPORT_NAME = "RAW_MODEL_CATALOG";

const SYNCED_PROVIDERS = new Set(["deepseek", "minimax-cn"]);

const sortRecord = (record) => {
  return Object.fromEntries(
    Object.keys(record)
      .sort()
      .map((key) => [key, record[key]]),
  );
};

async function main() {
  const res = await fetch(MODELS_DEV_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  /** @type {Record<string, {api?: string, models?: Record<string, any>}>} */
  const data = await res.json();

  /** @type {Record<string, { api: string, models: Record<string, any> }>} */
  const providers = {};

  for (const [providerKey, providerData] of Object.entries(data)) {
    if (!SYNCED_PROVIDERS.has(providerKey) || !providerData?.api || !providerData?.models) continue;

    /** @type {Record<string, any>} */
    const models = {};
    for (const [modelId, model] of Object.entries(providerData.models)) {
      if (model.tool_call !== true) continue;
      if (model.status === "deprecated") continue;

      models[modelId] = {
        id: modelId,
        name: model.name || modelId,
        reasoning: model.reasoning === true,
        input: model.modalities?.input?.includes("image") ? ["text", "image"] : ["text"],
        cost: {
          input: model.cost?.input ?? 0,
          output: model.cost?.output ?? 0,
          cacheRead: model.cost?.cache_read ?? 0,
          cacheWrite: model.cost?.cache_write ?? 0,
        },
        contextWindow: model.limit?.context ?? 4096,
        maxTokens: model.limit?.output ?? 4096,
      };
    }

    if (Object.keys(models).length > 0) {
      providers[providerKey] = {
        api: providerData.api,
        models,
      };
    }
  }

  const sortedProviders = sortRecord(
    Object.fromEntries(
      Object.entries(providers).map(([providerId, provider]) => [
        providerId,
        {
          ...provider,
          models: sortRecord(provider.models),
        },
      ]),
    ),
  );

  const serializedCatalog = JSON.stringify(sortedProviders, null, "\t");
  const output = [
    "// This file is auto-generated by apps/desktop/scripts/sync-models.mjs",
    "// Do not edit manually. Run `node scripts/sync-models.mjs` to update.",
    "",
    `export const ${RAW_CATALOG_EXPORT_NAME} = ${serializedCatalog} as const;`,
    "",
  ].join("\n");

  await writeFile(targetPath, output, "utf8");

  const total = Object.values(providers).reduce((sum, p) => sum + Object.keys(p.models).length, 0);
  console.log(`Synced ${total} models to ${targetPath}`);
}

main().catch(err => { console.error(err); process.exit(1); });
