import { writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const targetPath = join(__dirname, "..", "agent-bridge", "src", "llm", "models.original.ts");
const MODELS_DEV_URL = "https://models.dev/api.json";

/** @type {Record<string, { api: string, baseUrl: string }>} */
const PROVIDER_CONFIG = {
  deepseek: { api: "openai-completions", baseUrl: "https://api.deepseek.com" },
  "minimax-cn": { api: "anthropic-messages", baseUrl: "https://api.minimaxi.com/anthropic" },
};

async function main() {
  const res = await fetch(MODELS_DEV_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  /** @type {Record<string, {models?: Record<string, any>}>} */
  const data = await res.json();

  /** @type {Record<string, Record<string, any>>} */
  const providers = {};

  for (const [providerKey, providerData] of Object.entries(data)) {
    const config = PROVIDER_CONFIG[providerKey];
    if (!config || !providerData?.models) continue;

    /** @type {Record<string, any>} */
    const models = {};
    for (const [modelId, model] of Object.entries(providerData.models)) {
      if (model.tool_call !== true) continue;
      if (model.status === "deprecated") continue;

      models[modelId] = {
        id: modelId,
        name: model.name || modelId,
        api: config.api,
        provider: providerKey,
        baseUrl: config.baseUrl,
        reasoning: model.reasoning === true,
        input: model.modalities?.input?.includes("image") ? ["text", "image"] : ["text"],
        cost: {
          input: model.cost?.input ?? 0,
          output: model.cost?.output ?? 0,
          cacheRead: model.cost?.cache_read ?? 0,
          cacheWrite: model.cost?.cache_write ?? 0,
        },
        contextWindow: model.limit?.context ?? 4096,
        maxTokens: model.limit?.output ?? 4096,
      };
    }

    if (Object.keys(models).length > 0) {
      providers[providerKey] = models;
    }
  }

  let output = `// This file is auto-generated by apps/desktop/scripts/sync-models.mjs
// Do not edit manually. Run \`node scripts/sync-models.mjs\` to update.

export const MODEL_CATALOG = {
`;

  for (const providerId of Object.keys(providers).sort()) {
    const models = providers[providerId];
    output += `\t${JSON.stringify(providerId)}: {\n`;
    for (const modelId of Object.keys(models).sort()) {
      const m = models[modelId];
      output += `\t\t${JSON.stringify(m.id)}: {\n`;
      output += `\t\t\tid: ${JSON.stringify(m.id)},\n`;
      output += `\t\t\tname: ${JSON.stringify(m.name)},\n`;
      output += `\t\t\tapi: ${JSON.stringify(m.api)},\n`;
      output += `\t\t\tprovider: ${JSON.stringify(m.provider)},\n`;
      output += `\t\t\tbaseUrl: ${JSON.stringify(m.baseUrl)},\n`;
      output += `\t\t\treasoning: ${m.reasoning},\n`;
      output += `\t\t\tinput: [${m.input.map(i => JSON.stringify(i)).join(", ")}],\n`;
      output += `\t\t\tcost: { input: ${m.cost.input}, output: ${m.cost.output}, cacheRead: ${m.cost.cacheRead}, cacheWrite: ${m.cost.cacheWrite} },\n`;
      output += `\t\t\tcontextWindow: ${m.contextWindow},\n`;
      output += `\t\t\tmaxTokens: ${m.maxTokens},\n`;
      output += `\t\t},\n`;
    }
    output += `\t},\n`;
  }

  output += `};\n`;

  await writeFile(targetPath, output, "utf8");

  const total = Object.values(providers).reduce((sum, m) => sum + Object.keys(m).length, 0);
  console.log(`Synced ${total} models to ${targetPath}`);
}

main().catch(err => { console.error(err); process.exit(1); });