import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const desktopRoot = join(scriptDir, "..");
const repoRoot = join(desktopRoot, "..", "..");
const sourcePath = join(repoRoot, "ai", "pi", "packages", "ai", "src", "models.generated.ts");
const targetPath = join(desktopRoot, "src", "ai", "llm", "models.generated.ts");

const source = await readFile(sourcePath, "utf8");
const objectStart = source.indexOf("export const MODELS =");

if (objectStart < 0) {
  throw new Error(`Could not find MODELS export in ${sourcePath}`);
}

const objectText = source
  .slice(objectStart)
  .replace(/^export const MODELS =/, "export const MODEL_CATALOG =")
  .replaceAll(/\s+satisfies Model<[^>]+>/g, "");

const content = [
  "// This file is auto-generated by apps/desktop/scripts/sync-models.mjs",
  "// Do not edit manually. Run `pnpm --filter desktop sync-models` to update.",
  "",
  'import type { ModelCatalog } from "./model-catalog";',
  "",
  objectText.replace(/;\s*$/, " satisfies ModelCatalog;"),
  "",
].join("\n");

await writeFile(targetPath, content, "utf8");
console.log(`Synced model catalog to ${targetPath}`);
