// Retains the legacy configuration schema except for retired host roles.
export const CONFIG_SCHEMA_VERSION = 26;
export const configTables = [
  {
    name: "workspace_groups",
    columns: ["id", "name", "order", "is_default", "created_at", "updated_at"],
    sql: 'CREATE TABLE IF NOT EXISTS workspace_groups (\n    id TEXT PRIMARY KEY,\n    name TEXT NOT NULL UNIQUE,\n    "order" INTEGER DEFAULT 0,\n    is_default INTEGER DEFAULT 0,\n    created_at INTEGER NOT NULL,\n    updated_at INTEGER NOT NULL\n);',
  },
  {
    name: "workspaces",
    columns: [
      "id",
      "name",
      "description",
      "path",
      "is_pinned",
      "order",
      "group_id",
      "created_at",
      "updated_at",
    ],
    sql: 'CREATE TABLE IF NOT EXISTS workspaces (\n    id TEXT PRIMARY KEY,\n    name TEXT NOT NULL,\n    description TEXT,\n    path TEXT NOT NULL,\n    is_pinned INTEGER DEFAULT 0,\n    "order" INTEGER DEFAULT 0,\n    group_id TEXT,\n    created_at INTEGER NOT NULL,\n    updated_at INTEGER NOT NULL,\n    FOREIGN KEY (group_id) REFERENCES workspace_groups(id) ON DELETE SET NULL\n);',
  },
  {
    name: "stories",
    columns: ["id", "name", "workspace_path", "created_at", "updated_at"],
    sql: "CREATE TABLE IF NOT EXISTS stories (\n    id TEXT PRIMARY KEY,\n    name TEXT NOT NULL,\n    workspace_path TEXT NOT NULL UNIQUE,\n    created_at INTEGER NOT NULL,\n    updated_at INTEGER NOT NULL\n);",
  },
  {
    name: "llm_providers",
    columns: [
      "id",
      "name",
      "provider",
      "api_format",
      "api_key",
      "api_endpoint",
      "is_default",
      "created_at",
      "updated_at",
    ],
    sql: "CREATE TABLE IF NOT EXISTS llm_providers (\n    id TEXT PRIMARY KEY,\n    name TEXT NOT NULL,\n    provider TEXT NOT NULL DEFAULT '',\n    api_format TEXT NOT NULL,\n    api_key TEXT,\n    api_endpoint TEXT,\n    is_default INTEGER DEFAULT 0,\n    created_at INTEGER NOT NULL,\n    updated_at INTEGER NOT NULL\n);",
  },
  {
    name: "provider_models",
    columns: [
      "id",
      "provider_id",
      "model_id",
      "model_name",
      "is_enabled",
      "is_one_million_context",
      "thinking_json",
      "created_at",
      "updated_at",
    ],
    sql: "CREATE TABLE IF NOT EXISTS provider_models (\n    id TEXT PRIMARY KEY,\n    provider_id TEXT NOT NULL,\n    model_id TEXT NOT NULL,\n    model_name TEXT NOT NULL,\n    is_enabled INTEGER DEFAULT 1,\n    is_one_million_context INTEGER DEFAULT 0,\n    thinking_json TEXT,\n    created_at INTEGER NOT NULL,\n    updated_at INTEGER NOT NULL,\n    FOREIGN KEY (provider_id) REFERENCES llm_providers(id) ON DELETE CASCADE,\n    UNIQUE(provider_id, model_id)\n);",
  },
  {
    name: "skill_groups",
    columns: ["id", "name", "description", "order", "created_at", "updated_at"],
    sql: 'CREATE TABLE IF NOT EXISTS skill_groups (\n    id TEXT PRIMARY KEY,\n    name TEXT NOT NULL UNIQUE,\n    description TEXT,\n    "order" INTEGER NOT NULL DEFAULT 0,\n    created_at INTEGER NOT NULL,\n    updated_at INTEGER NOT NULL\n);',
  },
  {
    name: "skill_settings",
    columns: ["key", "value", "updated_at"],
    sql: "CREATE TABLE IF NOT EXISTS skill_settings (\n    key TEXT PRIMARY KEY,\n    value TEXT NOT NULL,\n    updated_at INTEGER NOT NULL\n);",
  },
  {
    name: "skill_group_skills",
    columns: ["group_id", "skill_name", "disabled", "created_at"],
    sql: "CREATE TABLE IF NOT EXISTS skill_group_skills (\n    group_id TEXT NOT NULL,\n    skill_name TEXT NOT NULL,\n    disabled INTEGER NOT NULL DEFAULT 0,\n    created_at INTEGER NOT NULL,\n    PRIMARY KEY(group_id, skill_name),\n    FOREIGN KEY(group_id) REFERENCES skill_groups(id) ON DELETE CASCADE\n);",
  },
  {
    name: "agent_definitions",
    columns: ["id", "definition_json", "created_at", "updated_at"],
    sql: "CREATE TABLE IF NOT EXISTS agent_definitions (id TEXT PRIMARY KEY, definition_json TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);",
  },
  {
    // Retired host workflow data is retained only for v25 database compatibility.
    name: "collaboration_workflows",
    columns: [
      "id",
      "name",
      "description",
      "writer_agent_id",
      "reviewer_agent_id",
      "draft_instruction",
      "review_instruction",
      "revise_instruction",
      "steps_json",
      "created_at",
      "updated_at",
    ],
    sql: "CREATE TABLE IF NOT EXISTS collaboration_workflows (\n    id TEXT PRIMARY KEY,\n    name TEXT NOT NULL,\n    description TEXT,\n    writer_agent_id TEXT NOT NULL,\n    reviewer_agent_id TEXT NOT NULL,\n    draft_instruction TEXT,\n    review_instruction TEXT,\n    revise_instruction TEXT,\n    steps_json TEXT,\n    created_at INTEGER NOT NULL,\n    updated_at INTEGER NOT NULL\n);",
  },
  {
    name: "agent_runtime_settings",
    columns: ["key", "value_json", "updated_at"],
    sql: "CREATE TABLE IF NOT EXISTS agent_runtime_settings (\n    key TEXT PRIMARY KEY,\n    value_json TEXT NOT NULL,\n    updated_at INTEGER NOT NULL\n);",
  },
  {
    name: "knowledge_collections",
    columns: [
      "id",
      "name",
      "description",
      "source_directory",
      "color",
      "order",
      "enabled",
      "embedding_profile_id",
      "created_at",
      "updated_at",
    ],
    sql: 'CREATE TABLE IF NOT EXISTS knowledge_collections (\n    id TEXT PRIMARY KEY,\n    name TEXT NOT NULL,\n    description TEXT,\n    source_directory TEXT,\n    color TEXT,\n    "order" INTEGER NOT NULL DEFAULT 0,\n    enabled INTEGER NOT NULL DEFAULT 1,\n    embedding_profile_id TEXT,\n    created_at INTEGER NOT NULL,\n    updated_at INTEGER NOT NULL,\n    UNIQUE(name)\n);',
  },
  {
    name: "knowledge_sources",
    columns: [
      "id",
      "kind",
      "uri",
      "title",
      "description",
      "enabled",
      "include_patterns_json",
      "exclude_patterns_json",
      "metadata_json",
      "created_at",
      "updated_at",
    ],
    sql: "CREATE TABLE IF NOT EXISTS knowledge_sources (\n    id TEXT PRIMARY KEY,\n    kind TEXT NOT NULL,\n    uri TEXT NOT NULL,\n    title TEXT NOT NULL,\n    description TEXT,\n    enabled INTEGER NOT NULL DEFAULT 1,\n    include_patterns_json TEXT,\n    exclude_patterns_json TEXT,\n    metadata_json TEXT,\n    created_at INTEGER NOT NULL,\n    updated_at INTEGER NOT NULL,\n    UNIQUE(kind, uri)\n);",
  },
  {
    name: "knowledge_collection_sources",
    columns: ["collection_id", "source_id", "created_at"],
    sql: "CREATE TABLE IF NOT EXISTS knowledge_collection_sources (\n    collection_id TEXT NOT NULL,\n    source_id TEXT NOT NULL,\n    created_at INTEGER NOT NULL,\n    PRIMARY KEY(collection_id, source_id),\n    FOREIGN KEY(collection_id) REFERENCES knowledge_collections(id) ON DELETE CASCADE,\n    FOREIGN KEY(source_id) REFERENCES knowledge_sources(id) ON DELETE CASCADE\n);",
  },
  {
    name: "knowledge_settings",
    columns: ["key", "value_json", "updated_at"],
    sql: "CREATE TABLE IF NOT EXISTS knowledge_settings (\n    key TEXT PRIMARY KEY,\n    value_json TEXT NOT NULL,\n    updated_at INTEGER NOT NULL\n);",
  },
  {
    name: "embedding_profiles",
    columns: [
      "id",
      "name",
      "provider_kind",
      "base_url",
      "api_key",
      "model_id",
      "dimensions",
      "batch_size",
      "is_default",
      "created_at",
      "updated_at",
    ],
    sql: "CREATE TABLE IF NOT EXISTS embedding_profiles (\n    id TEXT PRIMARY KEY,\n    name TEXT NOT NULL,\n    provider_kind TEXT NOT NULL,\n    base_url TEXT,\n    api_key TEXT,\n    model_id TEXT NOT NULL,\n    dimensions INTEGER NOT NULL,\n    batch_size INTEGER NOT NULL DEFAULT 64,\n    is_default INTEGER NOT NULL DEFAULT 0,\n    created_at INTEGER NOT NULL,\n    updated_at INTEGER NOT NULL\n);",
  },
] as const;
export const configSchema = configTables.map((t) => t.sql).join("\n");
