// @generated by protocol/scripts/generate-bindings.mjs
// Sources: protocol/v1/schema/*.schema.json and protocol/v1/openrpc.json
// Do not edit this file directly.
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Any JSON-RPC message crossing the agent runtime stdio boundary.
 */
export type AgentRuntimeMessage =
  IsleAgentRuntimeJSONRPCRequest | IsleAgentRuntimeJSONRPCResponse | IsleAgentRuntimeJSONRPCNotification;
export type IsleAgentRuntimeJSONRPCRequest = {
  jsonrpc: "2.0";
  id?: string | number;
  method: string;
  params?: {
    [k: string]: unknown;
  };
} & (
  | RuntimePingRequest
  | RuntimeShutdownRequest
  | AgentToolsListRequest
  | RuntimeModelsListRequest
  | AgentChatRequest
  | AgentRunRequest
  | AnswerQuestionRequest
  | SessionReadRequest
  | AgentSessionCompactRequest
  | AgentSessionRebuildRequest
  | SessionSummarizeRequest
  | AgentSessionSummarizeRequest
  | MessageEditRequest
  | MessageDeleteRequest
  | MessageAppendRequest
  | SessionRebuildRequest
  | RuntimeSessionsListRequest
  | RuntimeSessionReadRequest
  | RuntimeSessionDebugReadRequest
  | CollaborationTimelineReadRequest
  | CollaborationModesListRequest
  | CollaborationRunRequest
  | CollaborationModeRunRequest
);
export type AgentRuntimePlugin = {
  [k: string]: unknown;
} & {
  kind: "isle" | "dsh";
  id: string;
  entry: string;
  packageRoot: string;
  patchPath?: string;
  config?: {
    [k: string]: unknown;
  } | null;
};
export type StringArray = string[];
export type IsleAgentRuntimeJSONRPCResponse =
  | {
      jsonrpc: "2.0";
      id: string | number;
      result: AgentRuntimeResult;
    }
  | {
      jsonrpc: "2.0";
      id: string | number | null;
      error: {
        code: number;
        message: string;
        data?: unknown;
      };
    };
export type AgentRuntimeResult =
  | AckResult
  | AgentToolsResult
  | ChatResult
  | CollaborationModesResult
  | CollaborationResult
  | CollaborationTimelineResult
  | PongResult
  | RuntimeModelsResult
  | RuntimeSessionDebugResult
  | RuntimeSessionResult
  | RuntimeSessionsResult
  | SessionMutationResult
  | SessionResult
  | ShutdownAckResult
  | TaskResult;
export type IsleAgentRuntimeJSONRPCNotification =
  | {
      jsonrpc: "2.0";
      method: "runtime/event";
      params: AgentRuntimeEvent;
    }
  | {
      jsonrpc: "2.0";
      method: "runtime/result";
      params: AgentRuntimeResult;
    };
export type AgentRuntimeEvent =
  | StartedEvent
  | QuestionEvent
  | QuestionAnsweredEvent
  | ReplaceTextEvent
  | TextDeltaEvent
  | ThinkingDeltaEvent
  | ThinkingEndEvent
  | ToolCallStartEvent
  | ToolCallDeltaEvent
  | ToolCallEndEvent
  | ToolExecutionStartEvent
  | ToolExecutionUpdateEvent
  | ToolExecutionEndEvent
  | DoneEvent
  | AgentErrorEvent
  | WorkflowStartedEvent
  | StepStartedEvent
  | CollaborationAgentEvent
  | StepDoneEvent
  | StepSkippedEvent
  | WorkflowDoneEvent
  | CollaborationErrorEvent;

export interface RuntimePingRequest {
  method?: "runtime/ping";
  params?: EmptyParams;
  [k: string]: unknown;
}
export interface EmptyParams {}
export interface RuntimeShutdownRequest {
  method?: "runtime/shutdown";
  params?: EmptyParams;
  [k: string]: unknown;
}
export interface AgentToolsListRequest {
  method?: "agent/tools/list";
  params?: EmptyParams;
  [k: string]: unknown;
}
export interface RuntimeModelsListRequest {
  method?: "runtime/models/list";
  params?: EmptyParams;
  [k: string]: unknown;
}
export interface AgentChatRequest {
  method?: "agent/chat";
  params: ChatParams;
  [k: string]: unknown;
}
export interface ChatParams {
  streamId?: string | null;
  stream?: boolean;
  runtimeModel?: RuntimeModelInput | null;
  systemPrompt?: string | null;
  messages: ChatMessage[];
}
export interface RuntimeModelInput {
  provider: string;
  apiFormat:
    | "anthropic-messages"
    | "openai-completions"
    | "openai-codex-responses"
    | "openai-responses"
    | "azure-openai-responses"
    | "google-generative-ai"
    | "openrouter";
  apiKey?: string | null;
  catalogModelId: string;
  modelId: string;
  apiEndpoint?: string | null;
  reasoning?: boolean;
  thinkingLevel?: ("off" | "minimal" | "low" | "medium" | "high" | "xhigh") | null;
  thinkingLevelMap?: {
    [k: string]: string | null;
  };
  input?: ("text" | "image")[];
  cost?: RuntimeModelCost;
  contextWindow?: number;
  maxTokens?: number;
  headers?: {
    [k: string]: string;
  };
}
export interface RuntimeModelCost {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
}
export interface ChatMessage {
  role: string;
  content: string;
}
export interface AgentRunRequest {
  method?: "agent/run";
  params: AgentRunParams;
  [k: string]: unknown;
}
export interface AgentRunParams {
  taskId: string;
  workspacePath: string;
  sessionRootDir?: string | null;
  agentRoleId?: string | null;
  userMessage: string;
  recordUserMessage?: boolean | null;
  systemPrompt?: string | null;
  requestContext?: string | null;
  runtimeInstruction?: string | null;
  bootstrapInstruction?: string | null;
  runtimeModel?: RuntimeModelInput | null;
  resources?: AgentRuntimeResources | null;
}
export interface AgentRuntimeResources {
  tools?: AgentRuntimeToolResources | null;
  skills?: AgentRuntimeSkillResources | null;
  mcp?: AgentRuntimeMcpResources | null;
  plugins?: AgentRuntimePluginResources | null;
}
export interface AgentRuntimeToolResources {
  allowed?: string[] | null;
}
export interface AgentRuntimeSkillResources {
  bundledPath?: string | string[] | null;
  paths?: string[] | null;
  enabled?: string[] | null;
}
export interface AgentRuntimeMcpResources {
  servers?: unknown[];
  [k: string]: unknown;
}
export interface AgentRuntimePluginResources {
  settingsPath?: string | null;
  items?: AgentRuntimePlugin[] | null;
}
export interface AnswerQuestionRequest {
  method?: "agent/question/answer";
  params: AnswerQuestionParams;
  [k: string]: unknown;
}
export interface AnswerQuestionParams {
  taskId: string;
  questionId: string;
  answer: string;
}
export interface SessionReadRequest {
  method?: "session/read";
  params: SessionTargetParams;
  [k: string]: unknown;
}
export interface SessionTargetParams {
  workspacePath: string;
  sessionRootDir: string;
}
export interface AgentSessionCompactRequest {
  method?: "session/agent/compact";
  params: AgentSessionMaintenanceParams;
  [k: string]: unknown;
}
export interface AgentSessionMaintenanceParams {
  workspacePath: string;
  sessionRootDir: string;
  target: AgentTarget;
  options?: {
    [k: string]: unknown;
  } | null;
  runtime?: {
    [k: string]: unknown;
  } | null;
}
export interface AgentTarget {
  scope: "agent";
  agentRoleId: string;
}
export interface AgentSessionRebuildRequest {
  method?: "session/agent/rebuild";
  params: AgentSessionMaintenanceParams;
  [k: string]: unknown;
}
export interface SessionSummarizeRequest {
  method?: "session/summarize";
  params: SessionSummaryParams;
  [k: string]: unknown;
}
export interface SessionSummaryParams {
  workspacePath: string;
  sessionRootDir: string;
  options?: {
    [k: string]: unknown;
  } | null;
  runtime?: {
    [k: string]: unknown;
  } | null;
}
export interface AgentSessionSummarizeRequest {
  method?: "session/agent/summarize";
  params: AgentSessionSummaryParams;
  [k: string]: unknown;
}
export interface AgentSessionSummaryParams {
  workspacePath: string;
  sessionRootDir: string;
  target: AgentTarget;
  options?: {
    [k: string]: unknown;
  } | null;
  runtime?: {
    [k: string]: unknown;
  } | null;
}
export interface MessageEditRequest {
  method?: "session/message/edit";
  params: MessageEditParams;
  [k: string]: unknown;
}
export interface MessageEditParams {
  workspacePath: string;
  sessionRootDir: string;
  messageRecordId: string;
  content: string;
}
export interface MessageDeleteRequest {
  method?: "session/message/delete";
  params: MessageDeleteParams;
  [k: string]: unknown;
}
export interface MessageDeleteParams {
  workspacePath: string;
  sessionRootDir: string;
  messageRecordId: string;
}
export interface MessageAppendRequest {
  method?: "session/message/append";
  params: SessionMessagesParams;
  [k: string]: unknown;
}
export interface SessionMessagesParams {
  workspacePath: string;
  sessionRootDir: string;
  messages: SessionMessage[];
}
export interface SessionMessage {
  role: string;
  content: string;
  timestamp?: number | null;
  metadata?: {
    [k: string]: unknown;
  } | null;
}
export interface SessionRebuildRequest {
  method?: "session/rebuild";
  params: SessionMessagesParams;
  [k: string]: unknown;
}
export interface RuntimeSessionsListRequest {
  method?: "runtime/sessions/list";
  params: RuntimeSessionsParams;
  [k: string]: unknown;
}
export interface RuntimeSessionsParams {
  workspacePath: string;
  rootDir: string;
  limit?: number | null;
  maxDepth?: number | null;
}
export interface RuntimeSessionReadRequest {
  method?: "runtime/session/read";
  params: RuntimeSessionParams;
  [k: string]: unknown;
}
export interface RuntimeSessionParams {
  workspacePath: string;
  sessionRootDir: string;
  includeTimeline?: boolean | null;
  timelineLimit?: number | null;
}
export interface RuntimeSessionDebugReadRequest {
  method?: "runtime/session/debug/read";
  params: RuntimeSessionDebugParams;
  [k: string]: unknown;
}
export interface RuntimeSessionDebugParams {
  workspacePath: string;
  sessionRootDir: string;
  includeLedger?: boolean | null;
  includeTrace?: boolean | null;
  traceLimit?: number | null;
}
export interface CollaborationTimelineReadRequest {
  method?: "collaboration/timeline/read";
  params: CollaborationTimelineParams;
  [k: string]: unknown;
}
export interface CollaborationTimelineParams {
  workspacePath: string;
  sessionRootDir: string;
  workflowRunId?: string | null;
  limit?: number | null;
}
export interface CollaborationModesListRequest {
  method?: "collaboration/modes/list";
  params?: EmptyParams;
  [k: string]: unknown;
}
export interface CollaborationRunRequest {
  method?: "collaboration/run";
  params: CollaborationRunParams;
  [k: string]: unknown;
}
export interface CollaborationRunParams {
  requestId?: string | null;
  workspacePath: string;
  sessionRootDir?: string | null;
  workflow: Workflow;
  agents: CollaborationAgent[];
  resources?: AgentRuntimeResources | null;
  input?: unknown;
}
export interface Workflow {
  id: string;
  label?: string | null;
  version?: string | null;
  executionMode?: "serial" | "parallel" | null;
  maxSteps?: number | null;
  steps?: WorkflowStep[];
  metadata?: {
    [k: string]: unknown;
  } | null;
}
export interface WorkflowStep {
  id: string;
  type: "agent" | "dispatch" | "transform" | "condition" | "router";
  [k: string]: unknown;
}
export interface CollaborationAgent {
  id: string;
  label: string;
  systemPrompt?: string | null;
  runtimeModel?: RuntimeModelInput | null;
  allowedTools?: StringArray;
  enabledSkills?: StringArray;
  resources?: AgentRuntimeResources | null;
}
export interface CollaborationModeRunRequest {
  method?: "collaboration/runMode";
  params: CollaborationModeRunParams;
  [k: string]: unknown;
}
export interface CollaborationModeRunParams {
  requestId?: string | null;
  workspacePath: string;
  sessionRootDir?: string | null;
  mode: string;
  participants: CollaborationParticipant[];
  context?: unknown;
  options?: {
    [k: string]: unknown;
  } | null;
  resources?: AgentRuntimeResources | null;
}
export interface CollaborationParticipant {
  id: string;
  kind: string;
  [k: string]: unknown;
}
export interface AckResult {
  type: "ack";
  rpcRequestId?: string | number;
}
export interface AgentToolsResult {
  type: "agent_tools";
  rpcRequestId?: string | number;
  tools: AgentTool[];
  defaultToolNames: string[];
}
export interface AgentTool {
  name: string;
  label: string;
  description?: string | null;
  enabledByDefault: boolean;
}
export interface ChatResult {
  type: "chat_result";
  rpcRequestId?: string | number;
  text: string;
  thinking?: string | null;
}
export interface CollaborationModesResult {
  type: "collaboration_modes_result";
  rpcRequestId?: string | number;
  modes: CollaborationMode[];
}
export interface CollaborationMode {
  id: string;
  label: string;
  version: string;
}
export interface CollaborationResult {
  type: "collaboration_result";
  rpcRequestId?: string | number;
  workflowRunId: string;
  steps: CollaborationStepResult[];
  skippedSteps?: CollaborationSkippedStep[];
  output?: unknown;
  mode?: string | null;
  success?: boolean;
  message?: string;
}
export interface CollaborationStepResult {
  stepId: string;
  stepType: "agent" | "dispatch" | "transform" | "condition" | "router";
  outputKey: string;
  output: unknown;
  text: string;
  agentRoleId?: string;
  agentTaskId?: string;
  route?: string | null;
}
export interface CollaborationSkippedStep {
  stepId: string;
  reason: string;
  condition?: {
    [k: string]: unknown;
  } | null;
}
export interface CollaborationTimelineResult {
  type: "collaboration_timeline_result";
  rpcRequestId?: string | number;
  session: RuntimeSessionSummary;
  workflowRunId?: string | null;
  events: RuntimeTimelineItem[];
}
export interface RuntimeSessionSummary {
  workspacePath: string;
  sessionRootDir: string;
  sessionId?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  leafId?: string | null;
  entryCount: number;
  traceCount: number;
  workflowRunIds: string[];
  workflowIds: string[];
  modeIds: string[];
  latestWorkflowRunId?: string | null;
}
export interface RuntimeTimelineItem {
  id: string;
  index: number;
  source: "agent" | "collaboration" | "runtime";
  type: string;
  timestamp?: string | null;
  taskId?: string | null;
  workflowRunId?: string | null;
  workflowId?: string | null;
  modeId?: string | null;
  stepId?: string | null;
  stepType?: string | null;
  agentRoleId?: string | null;
  agentTaskId?: string | null;
  status?: "started" | "done" | "skipped" | "error" | null;
  detail?: string | null;
}
export interface PongResult {
  type: "pong";
  rpcRequestId?: string | number;
}
export interface RuntimeModelsResult {
  type: "runtime_models";
  rpcRequestId?: string | number;
  catalog: RuntimeModelCatalog;
}
export interface RuntimeModelCatalog {
  [k: string]: RuntimeModelProviderSummary;
}
export interface RuntimeModelProviderSummary {
  models: {
    [k: string]: RuntimeModelSummary;
  };
  websiteUrl: string;
  apis: RuntimeModelCatalogApi[];
}
export interface RuntimeModelSummary {
  id: string;
  name: string;
  reasoning: boolean;
  thinkingLevelMap?: {
    [k: string]: string | null;
  };
  input: ("text" | "image")[];
  cost: RuntimeModelCost;
  contextWindow: number;
  maxTokens: number;
  headers?: {
    [k: string]: string;
  };
}
export interface RuntimeModelCatalogApi {
  apiFormat:
    | "anthropic-messages"
    | "openai-completions"
    | "openai-codex-responses"
    | "openai-responses"
    | "azure-openai-responses"
    | "google-generative-ai"
    | "openrouter";
  apiEndpoint?: string;
}
export interface RuntimeSessionDebugResult {
  type: "runtime_session_debug_result";
  rpcRequestId?: string | number;
  session: RuntimeSessionSummary;
  ledger?: {
    header: unknown;
    entries: unknown[];
  } | null;
  trace?: unknown[];
}
export interface RuntimeSessionResult {
  type: "runtime_session_result";
  rpcRequestId?: string | number;
  session: RuntimeSessionSummary;
  timeline?: RuntimeTimelineItem[];
}
export interface RuntimeSessionsResult {
  type: "runtime_sessions_result";
  rpcRequestId?: string | number;
  sessions: RuntimeSessionSummary[];
}
export interface SessionMutationResult {
  type: "session_mutation_result";
  rpcRequestId?: string | number;
  sessionRootDir: string;
  summary: string;
  messages: RuntimeSessionMessage[];
  requestContexts?: RuntimeSessionAuxiliaryEntry[];
  runtimeInstructions?: RuntimeSessionAuxiliaryEntry[];
  displaySummary?: RuntimeDisplaySummary | null;
  displaySummaries?: RuntimeDisplaySummary[];
  runtimeLinks?: RuntimeLink[];
  messageRecordId?: string | null;
  messageRecordIds?: string[];
  compacted?: boolean;
  rebuilt?: boolean;
}
export interface RuntimeSessionMessage {
  messageRecordId: string;
  role: string;
  content: string;
  timestamp: number;
  metadata?: {
    [k: string]: unknown;
  } | null;
}
export interface RuntimeSessionAuxiliaryEntry {
  recordId: string;
  content: string;
  timestamp: number;
  metadata?: {
    [k: string]: unknown;
  } | null;
}
export interface RuntimeDisplaySummary {
  recordId: string;
  targetLeafId: string;
  summary: string;
  timestamp: number;
  generatedAt: number;
  summaryInstruction?: string | null;
  runtimeId?: string | null;
  modelId?: string | null;
  sourceCharCount?: number | null;
  chunkCount?: number | null;
  llmCallCount?: number | null;
  messageCount?: number | null;
  entryCount?: number | null;
}
export interface RuntimeLink {
  linkId: string;
  runtime?: string | null;
  runtimeId?: string | null;
  agentRoleId?: string | null;
  agentSessionId?: string | null;
  runId?: string | null;
  taskId?: string | null;
  streamId?: string | null;
  turnId?: string | null;
  parentEntryId?: string | null;
  rootUserEntryId?: string | null;
  systemMessageRecordId?: string | null;
  userMessageRecordId?: string | null;
  assistantMessageRecordIds: string[];
  requestContextRecordIds: string[];
  runtimeInstructionRecordIds: string[];
  messageRecordIds: string[];
  status?: "running" | "done" | "error" | null;
  startedAt?: number | null;
  endedAt?: number | null;
}
export interface SessionResult {
  type: "session_result";
  rpcRequestId?: string | number;
  sessionRootDir: string;
  summary: string;
  messages: RuntimeSessionMessage[];
  requestContexts?: RuntimeSessionAuxiliaryEntry[];
  runtimeInstructions?: RuntimeSessionAuxiliaryEntry[];
  displaySummary?: RuntimeDisplaySummary | null;
  displaySummaries?: RuntimeDisplaySummary[];
  runtimeLinks?: RuntimeLink[];
}
export interface ShutdownAckResult {
  type: "shutdown_ack";
  rpcRequestId?: string | number;
}
export interface TaskResult {
  type: "task_result";
  rpcRequestId?: string | number;
  taskId: string;
  success: boolean;
  message?: string;
}
export interface StartedEvent {
  type: "started";
  taskId: string;
}
export interface QuestionEvent {
  type: "question";
  taskId: string;
  questionId: string;
  question: string;
  context?: string | null;
  input?: AskUserInput;
}
export interface AskUserInput {
  type: "text" | "select";
  label?: string;
  options?: AskUserOption[];
  selected?: string;
}
export interface AskUserOption {
  value: string;
  label: string;
  description?: string;
}
export interface QuestionAnsweredEvent {
  type: "question_answered";
  taskId: string;
  questionId: string;
  answer: string;
}
export interface ReplaceTextEvent {
  type: "replace_text";
  taskId: string;
  text: string;
}
export interface TextDeltaEvent {
  type: "text_delta";
  taskId: string;
  delta: string;
}
export interface ThinkingDeltaEvent {
  type: "thinking_delta";
  taskId: string;
  delta: string;
}
export interface ThinkingEndEvent {
  type: "thinking_end";
  taskId: string;
  content: string;
}
export interface ToolCallStartEvent {
  type: "tool_call_start";
  taskId: string;
  toolCallId: string;
  toolName: string;
}
export interface ToolCallDeltaEvent {
  type: "tool_call_delta";
  taskId: string;
  toolCallId: string;
  toolName: string;
  delta: string;
}
export interface ToolCallEndEvent {
  type: "tool_call_end";
  taskId: string;
  toolCallId: string;
  toolName: string;
  args: unknown;
}
export interface ToolExecutionStartEvent {
  type: "tool_execution_start";
  taskId: string;
  toolCallId: string;
  toolName: string;
  args: unknown;
}
export interface ToolExecutionUpdateEvent {
  type: "tool_execution_update";
  taskId: string;
  toolCallId: string;
  toolName: string;
  partialResult: unknown;
}
export interface ToolExecutionEndEvent {
  type: "tool_execution_end";
  taskId: string;
  toolCallId: string;
  toolName: string;
  isError: boolean;
  result: unknown;
}
export interface DoneEvent {
  type: "done";
  taskId: string;
  text: string;
  runtimeSession?: RuntimeSessionRef | null;
}
export interface RuntimeSessionRef {
  sessionRootDir: string;
  userMessageRecordId?: string | null;
  requestContextRecordId?: string | null;
  runtimeInstructionRecordId?: string | null;
  assistantMessageRecordId?: string | null;
}
export interface AgentErrorEvent {
  type: "error";
  taskId?: string;
  message: string;
}
export interface WorkflowStartedEvent {
  type: "workflow_started";
  workflowRunId: string;
  workflowId: string;
}
export interface StepStartedEvent {
  type: "step_started";
  workflowRunId: string;
  stepId: string;
  stepType: "agent" | "dispatch" | "transform" | "condition" | "router";
  agentRoleId?: string;
  agentTaskId?: string;
}
export interface CollaborationAgentEvent {
  type: "agent_event";
  workflowRunId: string;
  stepId: string;
  agentRoleId: string;
  agentTaskId: string;
  event:
    | StartedEvent
    | QuestionEvent
    | QuestionAnsweredEvent
    | ReplaceTextEvent
    | TextDeltaEvent
    | ThinkingDeltaEvent
    | ThinkingEndEvent
    | ToolCallStartEvent
    | ToolCallDeltaEvent
    | ToolCallEndEvent
    | ToolExecutionStartEvent
    | ToolExecutionUpdateEvent
    | ToolExecutionEndEvent
    | DoneEvent
    | AgentErrorEvent;
}
export interface StepDoneEvent {
  type: "step_done";
  workflowRunId: string;
  step: CollaborationStepResult;
}
export interface StepSkippedEvent {
  type: "step_skipped";
  workflowRunId: string;
  step: CollaborationSkippedStep;
}
export interface WorkflowDoneEvent {
  type: "workflow_done";
  workflowRunId: string;
  result: {
    workflowRunId: string;
    steps: CollaborationStepResult[];
    skippedSteps?: CollaborationSkippedStep[];
    output?: unknown;
  };
}
export interface CollaborationErrorEvent {
  type: "error";
  workflowRunId: string;
  stepId?: string;
  agentRoleId?: string;
  agentTaskId?: string;
  message: string;
}

export const agentRuntimeProtocolVersion = "1.0.0" as const;
export const agentRuntimeJsonRpcMethods = [
  "runtime/ping",
  "runtime/shutdown",
  "agent/tools/list",
  "runtime/models/list",
  "agent/chat",
  "agent/run",
  "agent/question/answer",
  "session/read",
  "session/agent/compact",
  "session/agent/rebuild",
  "session/summarize",
  "session/agent/summarize",
  "session/message/edit",
  "session/message/delete",
  "session/message/append",
  "session/rebuild",
  "runtime/sessions/list",
  "runtime/session/read",
  "runtime/session/debug/read",
  "collaboration/timeline/read",
  "collaboration/modes/list",
  "collaboration/run",
  "collaboration/runMode",
] as const;
export const agentRuntimeNotificationMethods = ["runtime/event", "runtime/result"] as const;
export type AgentRuntimeJsonRpcMethod = (typeof agentRuntimeJsonRpcMethods)[number];
export type AgentRuntimeNotificationMethod = (typeof agentRuntimeNotificationMethods)[number];
export const RuntimeApiFormat = {
  AnthropicMessages: "anthropic-messages",
  OpenaiCompletions: "openai-completions",
  OpenaiCodexResponses: "openai-codex-responses",
  OpenaiResponses: "openai-responses",
  AzureOpenaiResponses: "azure-openai-responses",
  GoogleGenerativeAi: "google-generative-ai",
  Openrouter: "openrouter",
} as const;
export type RuntimeApiFormat = (typeof RuntimeApiFormat)[keyof typeof RuntimeApiFormat];
export const RuntimeThinkingLevel = {
  Off: "off",
  Minimal: "minimal",
  Low: "low",
  Medium: "medium",
  High: "high",
  Xhigh: "xhigh",
} as const;
export type RuntimeThinkingLevel = (typeof RuntimeThinkingLevel)[keyof typeof RuntimeThinkingLevel];
export const RuntimeModelInputModality = {
  Text: "text",
  Image: "image",
} as const;
export type RuntimeModelInputModality = (typeof RuntimeModelInputModality)[keyof typeof RuntimeModelInputModality];
export type AgentRuntimeRequestFor<TMethod extends AgentRuntimeJsonRpcMethod> = Extract<
  IsleAgentRuntimeJSONRPCRequest,
  { method?: TMethod }
>;
export type AgentRuntimeRequestParams<TMethod extends AgentRuntimeJsonRpcMethod> = NonNullable<
  AgentRuntimeRequestFor<TMethod>["params"]
>;
export const createAgentRuntimeRequest = <TMethod extends AgentRuntimeJsonRpcMethod>(
  id: string | number,
  method: TMethod,
  params: AgentRuntimeRequestParams<TMethod>,
): AgentRuntimeRequestFor<TMethod> => ({ jsonrpc: "2.0", id, method, params }) as AgentRuntimeRequestFor<TMethod>;
export const agentRuntimeRequests = {
  runtimePing: (id: string | number, params: AgentRuntimeRequestParams<"runtime/ping">) =>
    createAgentRuntimeRequest(id, "runtime/ping", params),
  runtimeShutdown: (id: string | number, params: AgentRuntimeRequestParams<"runtime/shutdown">) =>
    createAgentRuntimeRequest(id, "runtime/shutdown", params),
  agentToolsList: (id: string | number, params: AgentRuntimeRequestParams<"agent/tools/list">) =>
    createAgentRuntimeRequest(id, "agent/tools/list", params),
  runtimeModelsList: (id: string | number, params: AgentRuntimeRequestParams<"runtime/models/list">) =>
    createAgentRuntimeRequest(id, "runtime/models/list", params),
  agentChat: (id: string | number, params: AgentRuntimeRequestParams<"agent/chat">) =>
    createAgentRuntimeRequest(id, "agent/chat", params),
  agentRun: (id: string | number, params: AgentRuntimeRequestParams<"agent/run">) =>
    createAgentRuntimeRequest(id, "agent/run", params),
  agentQuestionAnswer: (id: string | number, params: AgentRuntimeRequestParams<"agent/question/answer">) =>
    createAgentRuntimeRequest(id, "agent/question/answer", params),
  sessionRead: (id: string | number, params: AgentRuntimeRequestParams<"session/read">) =>
    createAgentRuntimeRequest(id, "session/read", params),
  sessionAgentCompact: (id: string | number, params: AgentRuntimeRequestParams<"session/agent/compact">) =>
    createAgentRuntimeRequest(id, "session/agent/compact", params),
  sessionAgentRebuild: (id: string | number, params: AgentRuntimeRequestParams<"session/agent/rebuild">) =>
    createAgentRuntimeRequest(id, "session/agent/rebuild", params),
  sessionSummarize: (id: string | number, params: AgentRuntimeRequestParams<"session/summarize">) =>
    createAgentRuntimeRequest(id, "session/summarize", params),
  sessionAgentSummarize: (id: string | number, params: AgentRuntimeRequestParams<"session/agent/summarize">) =>
    createAgentRuntimeRequest(id, "session/agent/summarize", params),
  sessionMessageEdit: (id: string | number, params: AgentRuntimeRequestParams<"session/message/edit">) =>
    createAgentRuntimeRequest(id, "session/message/edit", params),
  sessionMessageDelete: (id: string | number, params: AgentRuntimeRequestParams<"session/message/delete">) =>
    createAgentRuntimeRequest(id, "session/message/delete", params),
  sessionMessageAppend: (id: string | number, params: AgentRuntimeRequestParams<"session/message/append">) =>
    createAgentRuntimeRequest(id, "session/message/append", params),
  sessionRebuild: (id: string | number, params: AgentRuntimeRequestParams<"session/rebuild">) =>
    createAgentRuntimeRequest(id, "session/rebuild", params),
  runtimeSessionsList: (id: string | number, params: AgentRuntimeRequestParams<"runtime/sessions/list">) =>
    createAgentRuntimeRequest(id, "runtime/sessions/list", params),
  runtimeSessionRead: (id: string | number, params: AgentRuntimeRequestParams<"runtime/session/read">) =>
    createAgentRuntimeRequest(id, "runtime/session/read", params),
  runtimeSessionDebugRead: (id: string | number, params: AgentRuntimeRequestParams<"runtime/session/debug/read">) =>
    createAgentRuntimeRequest(id, "runtime/session/debug/read", params),
  collaborationTimelineRead: (id: string | number, params: AgentRuntimeRequestParams<"collaboration/timeline/read">) =>
    createAgentRuntimeRequest(id, "collaboration/timeline/read", params),
  collaborationModesList: (id: string | number, params: AgentRuntimeRequestParams<"collaboration/modes/list">) =>
    createAgentRuntimeRequest(id, "collaboration/modes/list", params),
  collaborationRun: (id: string | number, params: AgentRuntimeRequestParams<"collaboration/run">) =>
    createAgentRuntimeRequest(id, "collaboration/run", params),
  collaborationRunMode: (id: string | number, params: AgentRuntimeRequestParams<"collaboration/runMode">) =>
    createAgentRuntimeRequest(id, "collaboration/runMode", params),
} as const;
export const AgentRuntimeEventType = {
  Started: "started",
  Question: "question",
  QuestionAnswered: "question_answered",
  ReplaceText: "replace_text",
  TextDelta: "text_delta",
  ThinkingDelta: "thinking_delta",
  ThinkingEnd: "thinking_end",
  ToolCallStart: "tool_call_start",
  ToolCallDelta: "tool_call_delta",
  ToolCallEnd: "tool_call_end",
  ToolExecutionStart: "tool_execution_start",
  ToolExecutionUpdate: "tool_execution_update",
  ToolExecutionEnd: "tool_execution_end",
  Done: "done",
  Error: "error",
  WorkflowStarted: "workflow_started",
  StepStarted: "step_started",
  AgentEvent: "agent_event",
  StepDone: "step_done",
  StepSkipped: "step_skipped",
  WorkflowDone: "workflow_done",
} as const;
export type AgentEvent = CollaborationAgentEvent["event"];
export type CollaborationEvent =
  | WorkflowStartedEvent
  | StepStartedEvent
  | CollaborationAgentEvent
  | StepDoneEvent
  | StepSkippedEvent
  | WorkflowDoneEvent
  | CollaborationErrorEvent;
export type AgentRuntimeEventType = (typeof AgentRuntimeEventType)[keyof typeof AgentRuntimeEventType];
export type AgentRuntimeEventOf<TType extends AgentRuntimeEventType> = Extract<AgentRuntimeEvent, { type: TType }>;
type AgentRuntimeEventPayloadFor<TEvent> = TEvent extends { type: AgentRuntimeEventType }
  ? Omit<TEvent, "type">
  : never;
export type AgentRuntimeEventPayload<TType extends AgentRuntimeEventType> = AgentRuntimeEventPayloadFor<
  AgentRuntimeEventOf<TType>
>;
export const isAgentRuntimeEventType = <TType extends AgentRuntimeEventType>(
  event: { type: string },
  type: TType,
): event is { type: TType } => event.type === type;
export const createAgentRuntimeEvent = <TType extends AgentRuntimeEventType>(
  type: TType,
  payload: AgentRuntimeEventPayload<TType>,
): AgentRuntimeEventOf<TType> => ({ type, ...payload }) as unknown as AgentRuntimeEventOf<TType>;
export const agentRuntimeEvents = {
  started: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.Started>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.Started, payload),
  question: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.Question>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.Question, payload),
  questionAnswered: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.QuestionAnswered>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.QuestionAnswered, payload),
  replaceText: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.ReplaceText>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.ReplaceText, payload),
  textDelta: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.TextDelta>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.TextDelta, payload),
  thinkingDelta: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.ThinkingDelta>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.ThinkingDelta, payload),
  thinkingEnd: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.ThinkingEnd>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.ThinkingEnd, payload),
  toolCallStart: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.ToolCallStart>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.ToolCallStart, payload),
  toolCallDelta: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.ToolCallDelta>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.ToolCallDelta, payload),
  toolCallEnd: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.ToolCallEnd>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.ToolCallEnd, payload),
  toolExecutionStart: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.ToolExecutionStart>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.ToolExecutionStart, payload),
  toolExecutionUpdate: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.ToolExecutionUpdate>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.ToolExecutionUpdate, payload),
  toolExecutionEnd: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.ToolExecutionEnd>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.ToolExecutionEnd, payload),
  done: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.Done>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.Done, payload),
  error: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.Error>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.Error, payload),
  workflowStarted: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.WorkflowStarted>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.WorkflowStarted, payload),
  stepStarted: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.StepStarted>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.StepStarted, payload),
  agentEvent: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.AgentEvent>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.AgentEvent, payload),
  stepDone: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.StepDone>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.StepDone, payload),
  stepSkipped: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.StepSkipped>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.StepSkipped, payload),
  workflowDone: (payload: AgentRuntimeEventPayload<typeof AgentRuntimeEventType.WorkflowDone>) =>
    createAgentRuntimeEvent(AgentRuntimeEventType.WorkflowDone, payload),
} as const;
export const agentRuntimeEventGuards = {
  started: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.Started } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.Started),
  question: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.Question } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.Question),
  questionAnswered: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.QuestionAnswered } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.QuestionAnswered),
  replaceText: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.ReplaceText } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.ReplaceText),
  textDelta: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.TextDelta } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.TextDelta),
  thinkingDelta: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.ThinkingDelta } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.ThinkingDelta),
  thinkingEnd: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.ThinkingEnd } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.ThinkingEnd),
  toolCallStart: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.ToolCallStart } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.ToolCallStart),
  toolCallDelta: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.ToolCallDelta } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.ToolCallDelta),
  toolCallEnd: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.ToolCallEnd } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.ToolCallEnd),
  toolExecutionStart: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.ToolExecutionStart } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.ToolExecutionStart),
  toolExecutionUpdate: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.ToolExecutionUpdate } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.ToolExecutionUpdate),
  toolExecutionEnd: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.ToolExecutionEnd } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.ToolExecutionEnd),
  done: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.Done } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.Done),
  error: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.Error } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.Error),
  workflowStarted: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.WorkflowStarted } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.WorkflowStarted),
  stepStarted: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.StepStarted } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.StepStarted),
  agentEvent: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.AgentEvent } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.AgentEvent),
  stepDone: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.StepDone } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.StepDone),
  stepSkipped: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.StepSkipped } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.StepSkipped),
  workflowDone: (event: { type: string }): event is { type: typeof AgentRuntimeEventType.WorkflowDone } =>
    isAgentRuntimeEventType(event, AgentRuntimeEventType.WorkflowDone),
} as const;
export const AgentRuntimeResultType = {
  Ack: "ack",
  AgentTools: "agent_tools",
  ChatResult: "chat_result",
  Pong: "pong",
  ShutdownAck: "shutdown_ack",
  TaskResult: "task_result",
  RuntimeModels: "runtime_models",
  SessionResult: "session_result",
  SessionMutationResult: "session_mutation_result",
  CollaborationResult: "collaboration_result",
  CollaborationModesResult: "collaboration_modes_result",
  RuntimeSessionsResult: "runtime_sessions_result",
  RuntimeSessionResult: "runtime_session_result",
  RuntimeSessionDebugResult: "runtime_session_debug_result",
  CollaborationTimelineResult: "collaboration_timeline_result",
} as const;
export type AgentRuntimeResultType = (typeof AgentRuntimeResultType)[keyof typeof AgentRuntimeResultType];
export type AgentRuntimeResultOf<TType extends AgentRuntimeResultType> = Extract<AgentRuntimeResult, { type: TType }>;
type AgentRuntimeResultPayloadFor<TResult> = TResult extends { type: AgentRuntimeResultType }
  ? Omit<TResult, "type">
  : never;
export type AgentRuntimeResultPayload<TType extends AgentRuntimeResultType> = AgentRuntimeResultPayloadFor<
  AgentRuntimeResultOf<TType>
>;
export const isAgentRuntimeResultType = <TType extends AgentRuntimeResultType>(
  result: { type: string },
  type: TType,
): result is { type: TType } => result.type === type;
export const createAgentRuntimeResult = <TType extends AgentRuntimeResultType>(
  type: TType,
  payload: AgentRuntimeResultPayload<TType>,
): AgentRuntimeResultOf<TType> => ({ type, ...payload }) as unknown as AgentRuntimeResultOf<TType>;
export const agentRuntimeResults = {
  ack: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.Ack>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.Ack, payload),
  agentTools: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.AgentTools>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.AgentTools, payload),
  chatResult: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.ChatResult>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.ChatResult, payload),
  pong: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.Pong>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.Pong, payload),
  shutdownAck: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.ShutdownAck>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.ShutdownAck, payload),
  taskResult: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.TaskResult>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.TaskResult, payload),
  runtimeModels: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.RuntimeModels>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.RuntimeModels, payload),
  sessionResult: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.SessionResult>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.SessionResult, payload),
  sessionMutationResult: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.SessionMutationResult>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.SessionMutationResult, payload),
  collaborationResult: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.CollaborationResult>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.CollaborationResult, payload),
  collaborationModesResult: (
    payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.CollaborationModesResult>,
  ) => createAgentRuntimeResult(AgentRuntimeResultType.CollaborationModesResult, payload),
  runtimeSessionsResult: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.RuntimeSessionsResult>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.RuntimeSessionsResult, payload),
  runtimeSessionResult: (payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.RuntimeSessionResult>) =>
    createAgentRuntimeResult(AgentRuntimeResultType.RuntimeSessionResult, payload),
  runtimeSessionDebugResult: (
    payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.RuntimeSessionDebugResult>,
  ) => createAgentRuntimeResult(AgentRuntimeResultType.RuntimeSessionDebugResult, payload),
  collaborationTimelineResult: (
    payload: AgentRuntimeResultPayload<typeof AgentRuntimeResultType.CollaborationTimelineResult>,
  ) => createAgentRuntimeResult(AgentRuntimeResultType.CollaborationTimelineResult, payload),
} as const;
export const agentRuntimeResultGuards = {
  ack: (result: { type: string }): result is { type: typeof AgentRuntimeResultType.Ack } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.Ack),
  agentTools: (result: { type: string }): result is { type: typeof AgentRuntimeResultType.AgentTools } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.AgentTools),
  chatResult: (result: { type: string }): result is { type: typeof AgentRuntimeResultType.ChatResult } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.ChatResult),
  pong: (result: { type: string }): result is { type: typeof AgentRuntimeResultType.Pong } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.Pong),
  shutdownAck: (result: { type: string }): result is { type: typeof AgentRuntimeResultType.ShutdownAck } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.ShutdownAck),
  taskResult: (result: { type: string }): result is { type: typeof AgentRuntimeResultType.TaskResult } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.TaskResult),
  runtimeModels: (result: { type: string }): result is { type: typeof AgentRuntimeResultType.RuntimeModels } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.RuntimeModels),
  sessionResult: (result: { type: string }): result is { type: typeof AgentRuntimeResultType.SessionResult } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.SessionResult),
  sessionMutationResult: (result: {
    type: string;
  }): result is { type: typeof AgentRuntimeResultType.SessionMutationResult } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.SessionMutationResult),
  collaborationResult: (result: {
    type: string;
  }): result is { type: typeof AgentRuntimeResultType.CollaborationResult } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.CollaborationResult),
  collaborationModesResult: (result: {
    type: string;
  }): result is { type: typeof AgentRuntimeResultType.CollaborationModesResult } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.CollaborationModesResult),
  runtimeSessionsResult: (result: {
    type: string;
  }): result is { type: typeof AgentRuntimeResultType.RuntimeSessionsResult } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.RuntimeSessionsResult),
  runtimeSessionResult: (result: {
    type: string;
  }): result is { type: typeof AgentRuntimeResultType.RuntimeSessionResult } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.RuntimeSessionResult),
  runtimeSessionDebugResult: (result: {
    type: string;
  }): result is { type: typeof AgentRuntimeResultType.RuntimeSessionDebugResult } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.RuntimeSessionDebugResult),
  collaborationTimelineResult: (result: {
    type: string;
  }): result is { type: typeof AgentRuntimeResultType.CollaborationTimelineResult } =>
    isAgentRuntimeResultType(result, AgentRuntimeResultType.CollaborationTimelineResult),
} as const;
