import { build } from "esbuild";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export async function buildRssUi() {
  await build({
    entryPoints: [resolve(root, "ui/main.tsx")],
    outfile: resolve(root, "mewvis-ui.js"),
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["es2022"],
    minify: true,
    legalComments: "eof",
    define: { "process.env.NODE_ENV": '"production"' },
    loader: { ".png": "dataurl", ".webp": "dataurl" },
    banner: { js: "// Generated by scripts/build-ui.mjs; edit ui/ instead." },
  });
}
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
)
  await buildRssUi();
