import { readFile, writeFile } from "node:fs/promises";
import { compile } from "json-schema-to-typescript";
import { uiSlotDefinitions, uiSlotTypes } from "../ui/slots.js";

const id = { type: "string", pattern: "^[a-z][a-z0-9-]*$", maxLength: 64 };
const schema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  $id: "urn:isle:ui-contribution",
  title: "UIContribution",
  oneOf: Object.values(uiSlotDefinitions).map((slot) => {
    const payload = uiSlotTypes[slot.type].schema;
    return {
      ...payload,
      required: ["id", "slot", "type", ...payload.required],
      properties: {
        id,
        slot: { const: slot.key },
        type: { const: slot.type },
        ...payload.properties,
      },
    };
  }),
};
const banner =
  "/* Generated by scripts/generate-ui.mjs from ui/slots.js. Do not edit. */";
const literal = (value) => JSON.stringify(value);
const types = await compile(schema, "UIContribution", {
  bannerComment: banner,
  unreachableDefinitions: true,
});
const declarations = `${types}\nexport const uiSlotDefinitions: {\n${Object.entries(
  uiSlotDefinitions,
)
  .map(
    ([name, slot]) =>
      `  readonly ${name}: { ${Object.entries(slot)
        .map(([key, value]) => `readonly ${key}: ${literal(value)}`)
        .join("; ")} };`,
  )
  .join("\n")}\n};\nexport const uiSlotTypes: {\n${Object.values(uiSlotTypes)
  .map(
    ({ type }) =>
      `  readonly ${type}: { readonly type: ${literal(type)}; readonly schema: object };`,
  )
  .join("\n")}\n};\n`;
for (const [name, content] of [
  ["ui/contribution.schema.json", `${JSON.stringify(schema, null, 2)}\n`],
  ["ui/slots.generated.d.ts", declarations],
]) {
  const file = new URL(`../${name}`, import.meta.url);
  if (process.argv.includes("--check")) {
    if ((await readFile(file, "utf8")) !== content)
      throw Error(`${name} is stale; run SDK generate`);
  } else await writeFile(file, content);
}
