import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const output = await build({
  entryPoints: [fileURLToPath(new URL("main/embedded-view.ts", root))],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  minify: true,
  write: false,
});
// Checked in so the shared built-in packer can consume the same standalone view.
const destination = new URL("main/embedded-view.generated.ts", root);
const source =
  "// Generated by pnpm prepare:view; edit embedded-view.ts instead.\nexport const embeddedScript = " +
  JSON.stringify(output.outputFiles[0].text) +
  ";\n";
if ((await readFile(destination, "utf8").catch(() => "")) !== source)
  await writeFile(destination, source);
