// Generated by pnpm sync-product-config. Do not edit.
export declare const PRODUCT_CONFIG: {
  readonly "displayName": "Mewvis";
  readonly "namespace": "mewvis";
  readonly "bundleName": "Mewvis";
  readonly "windowTitle": "Mewvis";
  readonly "appDataDirName": ".mewvis";
  readonly "defaultWorkspaceDirName": "default-workspace";
  readonly "storageKeyPrefix": "mewvis";
  readonly "envPrefix": "MEWVIS";
  readonly "versionControl": {
  readonly "authorName": "Mewvis";
  readonly "authorEmail": "mewvis@local";
};
  readonly "agentRuntimePackageName": "@mewvis/agent-runtime";
  readonly "bundleIdentifier": "com.mewvis.desktop";
  readonly "description": "Mewvis Desktop Client";
  readonly "assets": {
  readonly "brandMark": "/assets/startup/brand-mark.png";
};
  readonly "schemas": {
  readonly "applicationOrigin": "https://mewvis.app";
  readonly "runtimeOrigin": "https://mewvis.local";
};
  readonly "files": {
  readonly "appConfig": "app.config.ts";
  readonly "appUiScript": "app-ui.js";
  readonly "appUiStyle": "app-ui.css";
};
  readonly "cli": {
  readonly "application": "mewvis-app";
  readonly "extension": "mewvis-extension";
};
};
export declare const APP_DISPLAY_NAME: typeof PRODUCT_CONFIG.displayName;
export declare const APP_DATA_DIR_NAME: typeof PRODUCT_CONFIG.appDataDirName;
export declare const PRODUCT_NAMESPACE: typeof PRODUCT_CONFIG.namespace;
export declare const DEFAULT_WORKSPACE_DIR_NAME: typeof PRODUCT_CONFIG.defaultWorkspaceDirName;
export type ProductId<Suffix extends string = ""> = `${typeof PRODUCT_NAMESPACE}${Suffix}`;
export declare function productId<Suffix extends string = "">(suffix?: Suffix): ProductId<Suffix>;
export declare function productDataName<Suffix extends string = "">(suffix?: Suffix): `${typeof APP_DATA_DIR_NAME}${Suffix}`;
export declare function envName<Suffix extends string>(suffix: Suffix): `${typeof PRODUCT_CONFIG.envPrefix}_${Suffix}`;
export declare function appStorageKey(name: string): string;
export declare const PRODUCT_KEYS: {
  readonly "applicationManifest": "mewvis";
  readonly "extensionManifest": "mewvis.extension";
  readonly "pluginManifest": "mewvis.plugin";
  readonly "applicationGlobal": "mewvisApplication";
  readonly "applicationReactGlobal": "mewvisApplicationReact";
  readonly "applicationChatGlobal": "mewvisApplicationChatUI";
  readonly "embeddedViewGlobal": "mewvisEmbeddedView";
  readonly "applicationSettings": "$mewvisApplicationSettings";
  readonly "hostSettings": "$mewvisHost";
  readonly "runtimeCommand": "x-mewvis-command";
  readonly "runtimeParamsSchema": "x-mewvis-params-schema";
};
