// This file is auto-generated by apps/client/scripts/maintenance/sync-models.mjs
// Do not edit manually. Run `pnpm sync-models` to update.

export const RAW_MODEL_CATALOG = {
	"deepseek": {
		"api": "https://api.deepseek.com",
		"models": {
			"deepseek-chat": {
				"id": "deepseek-chat",
				"name": "DeepSeek Chat",
				"reasoning": false,
				"input": [
					"text"
				],
				"cost": {
					"input": 0.14,
					"output": 0.28,
					"cacheRead": 0.0028,
					"cacheWrite": 0
				},
				"contextWindow": 1000000,
				"maxTokens": 384000
			},
			"deepseek-reasoner": {
				"id": "deepseek-reasoner",
				"name": "DeepSeek Reasoner",
				"reasoning": true,
				"input": [
					"text"
				],
				"cost": {
					"input": 0.14,
					"output": 0.28,
					"cacheRead": 0.0028,
					"cacheWrite": 0
				},
				"contextWindow": 1000000,
				"maxTokens": 384000
			},
			"deepseek-v4-flash": {
				"id": "deepseek-v4-flash",
				"name": "DeepSeek V4 Flash",
				"reasoning": true,
				"input": [
					"text"
				],
				"cost": {
					"input": 0.14,
					"output": 0.28,
					"cacheRead": 0.0028,
					"cacheWrite": 0
				},
				"contextWindow": 1000000,
				"maxTokens": 384000
			},
			"deepseek-v4-pro": {
				"id": "deepseek-v4-pro",
				"name": "DeepSeek V4 Pro",
				"reasoning": true,
				"input": [
					"text"
				],
				"cost": {
					"input": 0.435,
					"output": 0.87,
					"cacheRead": 0.003625,
					"cacheWrite": 0
				},
				"contextWindow": 1000000,
				"maxTokens": 384000
			}
		}
	},
	"minimax-cn": {
		"api": "https://api.minimaxi.com/anthropic/v1",
		"models": {
			"MiniMax-M2": {
				"id": "MiniMax-M2",
				"name": "MiniMax-M2",
				"reasoning": true,
				"input": [
					"text"
				],
				"cost": {
					"input": 0.3,
					"output": 1.2,
					"cacheRead": 0,
					"cacheWrite": 0
				},
				"contextWindow": 196608,
				"maxTokens": 128000
			},
			"MiniMax-M2.1": {
				"id": "MiniMax-M2.1",
				"name": "MiniMax-M2.1",
				"reasoning": true,
				"input": [
					"text"
				],
				"cost": {
					"input": 0.3,
					"output": 1.2,
					"cacheRead": 0,
					"cacheWrite": 0
				},
				"contextWindow": 204800,
				"maxTokens": 131072
			},
			"MiniMax-M2.5": {
				"id": "MiniMax-M2.5",
				"name": "MiniMax-M2.5",
				"reasoning": true,
				"input": [
					"text"
				],
				"cost": {
					"input": 0.3,
					"output": 1.2,
					"cacheRead": 0.03,
					"cacheWrite": 0.375
				},
				"contextWindow": 204800,
				"maxTokens": 131072
			},
			"MiniMax-M2.5-highspeed": {
				"id": "MiniMax-M2.5-highspeed",
				"name": "MiniMax-M2.5-highspeed",
				"reasoning": true,
				"input": [
					"text"
				],
				"cost": {
					"input": 0.6,
					"output": 2.4,
					"cacheRead": 0.06,
					"cacheWrite": 0.375
				},
				"contextWindow": 204800,
				"maxTokens": 131072
			},
			"MiniMax-M2.7": {
				"id": "MiniMax-M2.7",
				"name": "MiniMax-M2.7",
				"reasoning": true,
				"input": [
					"text"
				],
				"cost": {
					"input": 0.3,
					"output": 1.2,
					"cacheRead": 0.06,
					"cacheWrite": 0.375
				},
				"contextWindow": 204800,
				"maxTokens": 131072
			},
			"MiniMax-M2.7-highspeed": {
				"id": "MiniMax-M2.7-highspeed",
				"name": "MiniMax-M2.7-highspeed",
				"reasoning": true,
				"input": [
					"text"
				],
				"cost": {
					"input": 0.6,
					"output": 2.4,
					"cacheRead": 0.06,
					"cacheWrite": 0.375
				},
				"contextWindow": 204800,
				"maxTokens": 131072
			},
			"MiniMax-M3": {
				"id": "MiniMax-M3",
				"name": "MiniMax-M3",
				"reasoning": true,
				"input": [
					"text",
					"image"
				],
				"cost": {
					"input": 0.3,
					"output": 1.2,
					"cacheRead": 0.06,
					"cacheWrite": 0
				},
				"contextWindow": 1000000,
				"maxTokens": 128000
			}
		}
	}
} as const;
