import {
  DEFAULT_TAVERN_INTERACTION_QUALITY_RULE_IDS,
} from "./prompt-registry/rule-layers/resolver";
import type {
  TavernProgressTrackerSettings,
  TavernProgressView,
  TavernRoomSettings,
  TavernSceneOutcomeDefinition,
  TavernStatusDefinition,
  TavernStatusRule,
  TavernTaskDefinition,
} from "./types";

export const DEFAULT_TAVERN_ROOM_SETTINGS: TavernRoomSettings = {
  immersiveDescriptionEnabled: true,
  showExecutionTrace: false,
  autoAssetExtractionEnabled: false,
  assetExtractionIntervalTurns: 3,
  maxAssetDrafts: 5,
  directorMaxSpeakers: 3,
  agentKnowledgeCompactIntervalTurns: 0,
  interactionQualityRuleIds: [...DEFAULT_TAVERN_INTERACTION_QUALITY_RULE_IDS],
  directorNarrativeControl: {
    agencyMode: "player_protagonist",
    responseScale: "balanced",
    narratorPressure: "balanced",
    eventInterruption: "auto",
    userActionConsequence: "visible",
    mainHook: "auto",
    qnaBreak: "auto",
  },
  directorScheduling: {
    targetedReplyPolicy: "prefer",
    maxExtraSpeakersOnTargetedReply: 2,
    allowDirectorOnly: false,
    directorOnlyPhaseStatusId: "",
    directorOnlyPhaseValues: [],
    speakerMotivation: {
      enabled: true,
      maxMotivatedSpeakers: 2,
      rules: [
        {
          id: "direct-target-priority",
          label: "直接目标优先",
          when: "用户明确询问、点名、选择候选回复目标，或上一位角色的问题明确指向某角色。",
          priority: 100,
          instruction: "被直接指向的角色必须优先被导演评估；若需要回应但不适合开口，应进入 nonverbalReplyIds 并由角色 Agent 输出心理和动作，不要改成旁白代替。只有完全无需近景反应时才不调度。",
        },
        {
          id: "goal-competes-for-user-attention",
          label: "目标竞争用户注意",
          when: "角色的个人任务、胜利条件、关系目标或当前人设目标与获得用户注意/好感/信任相关。",
          priority: 72,
          instruction: "即使用户没有点名，该角色也可以主动发言吸引用户注意，但不要每轮都抢话；根据人设克制程度决定是否加入。",
        },
        {
          id: "knowledge-holder-helps-or-misdirects",
          label: "知情者介入",
          when: "角色掌握与当前问题相关的公开事实、私有事实、阵营信息、线索或世界书知识。",
          priority: 68,
          instruction: "友好或守序角色倾向于补充帮助；有隐藏目标、敌对或欺骗动机的角色可误导、转移焦点或半真半假地发言，但不能泄露不该公开的事实。",
        },
        {
          id: "relationship-stakes",
          label: "关系利益相关",
          when: "当前发言会影响角色与用户或其他角色的好感、敌对、信任、承诺或竞争关系。",
          priority: 58,
          instruction: "关系利益越高，说话欲望越高；关系冷淡或无关的角色保持旁观或只做 ambient action。",
        },
        {
          id: "quiet-temperament-brake",
          label: "沉默人设刹车",
          when: "角色人设是寡言、谨慎、冷淡、观察者、守规矩，且没有被点名、没有关键事实、没有强利益相关。",
          priority: 25,
          instruction: "这类角色一般不要加入 speakerIds，可用 ambientActions 表示弱在场；但如果被点名或需要近景非语言反应，可加入 nonverbalReplyIds 并用角色动作完成本轮。",
        },
      ],
    },
    fixedOrder: {
      enabled: false,
      phaseStatusId: "",
      phaseValues: [],
      stopAfterRound: false,
      includeUser: false,
      userPosition: "first",
    },
    autoContinuation: "enabled",
    instruction: "",
  },
  continuation: {
    enabled: true,
    maxAutoContinuationRounds: 1,
    maxSpeakersPerContinuation: 1,
    stopWhenUserTargeted: true,
  },
  replyOptions: {
    enabled: true,
    count: 3,
  },
  statusTracking: {
    enabled: true,
    visibleToUser: true,
  },
  randomEvents: {
    enabled: false,
    probability: 0.15,
  },
  illustrationHints: {
    enabled: false,
  },
  informationPolicy: {
    mode: "open",
    uiDefaultView: "reveal",
    hideCharacterThoughts: false,
    revealThoughts: "manual",
    hiddenFacts: {
      enabled: false,
      defaultVisibility: "director",
      reveal: "manual",
    },
    roleAssignment: {
      enabled: false,
      strategy: "manual",
      includeUser: true,
      revealToAssignedCharacter: true,
      revealFactionMembers: true,
      rolePool: [],
      opening: {
        autoStart: false,
        publicEventType: "",
        globalStatusPatches: [],
      },
    },
  },
};

export const DEFAULT_TAVERN_PROGRESS_TRACKER: TavernProgressTrackerSettings = {
  enabled: false,
  mode: "manual",
  intervalTurns: 1,
  applyMode: "review",
  factConfidenceThreshold: 0.75,
  generateCheckpointBeforeContextTrim: true,
};

export const DEFAULT_TAVERN_PROGRESS_VIEWS: TavernProgressView[] = [
  {
    id: "scene-overview",
    label: "全局状态",
    kind: "status",
    placement: "sidePanel",
    ownerBinding: "scene",
    layout: "compact",
    compareWith: "previousTurn",
    items: [
      { type: "status", statusId: "scene_phase", display: "text", hiddenWhenDefault: true },
      { type: "status", statusId: "threat_level", display: "meter", showDelta: true },
    ],
  },
  {
    id: "character-vitals",
    label: "角色状态",
    kind: "status",
    placement: "characterCard",
    ownerBinding: "allCharacters",
    layout: "bars",
    compareWith: "previousTurn",
    items: [
      { type: "status", statusId: "health", display: "bar", showDelta: true },
      { type: "status", statusId: "san", display: "bar", showDelta: true },
    ],
  },
  {
    id: "scene-progress",
    label: "任务与结局",
    kind: "mixed",
    placement: "sidePanel",
    ownerBinding: "scene",
    layout: "questLog",
    compareWith: "previousTurn",
    items: [],
  },
  {
    id: "relationship-to-user",
    label: "对你的态度",
    kind: "status",
    placement: "composerBelow",
    ownerBinding: "allCharactersToUser",
    layout: "compact",
    compareWith: "previousTurn",
    items: [
      { type: "status", statusId: "favorability", display: "meter", showDelta: true },
      { type: "status", statusId: "hostility", display: "meter", showDelta: true },
    ],
  },
];

export const DEFAULT_TAVERN_STATUS_DEFINITIONS: TavernStatusDefinition[] = [
  {
    id: "scene_phase",
    label: "阶段",
    scope: "scene",
    valueType: "text",
    defaultValue: "",
    visibility: "public",
    updatePolicy: {
      mode: "manualOnly",
      requireFactEvent: false,
    },
  },
  {
    id: "threat_level",
    label: "威胁",
    scope: "scene",
    valueType: "number",
    defaultValue: 0,
    visibility: "public",
    min: 0,
    max: 100,
    updatePolicy: {
      mode: "eventDrivenWithReview",
      requireFactEvent: true,
      allowedEventTypes: ["threat", "stabilize"],
      maxDeltaPerTurn: 20,
      confidenceThreshold: 0.75,
    },
  },
  {
    id: "health",
    label: "健康",
    scope: "character",
    valueType: "number",
    defaultValue: 100,
    visibility: "public",
    min: 0,
    max: 100,
    updatePolicy: {
      mode: "eventDrivenWithReview",
      requireFactEvent: true,
      allowedEventTypes: ["damage", "healing"],
      maxDeltaPerTurn: 30,
      confidenceThreshold: 0.75,
    },
  },
  {
    id: "san",
    label: "理智",
    scope: "character",
    valueType: "number",
    defaultValue: 100,
    visibility: "private",
    min: 0,
    max: 100,
    updatePolicy: {
      mode: "eventDrivenWithReview",
      requireFactEvent: true,
      allowedEventTypes: ["sanityShock", "comfort", "rest"],
      maxDeltaPerTurn: 15,
      confidenceThreshold: 0.75,
    },
  },
  {
    id: "favorability",
    label: "好感",
    scope: "relationship",
    valueType: "number",
    defaultValue: 0,
    visibility: "private",
    min: -100,
    max: 100,
    relationship: {
      directed: true,
      allowedSubjectTypes: ["character", "user"],
      allowedObjectTypes: ["character", "user"],
    },
    updatePolicy: {
      mode: "eventDrivenWithReview",
      requireFactEvent: true,
      allowedEventTypes: ["help", "gift", "betrayal", "promiseKept", "promiseBroken", "dateAccepted", "dateRejected"],
      maxDeltaPerTurn: 5,
      confidenceThreshold: 0.8,
      manualReviewAboveDelta: 3,
    },
  },
  {
    id: "hostility",
    label: "敌对",
    scope: "relationship",
    valueType: "number",
    defaultValue: 0,
    visibility: "private",
    min: 0,
    max: 100,
    relationship: {
      directed: true,
      allowedSubjectTypes: ["character", "user"],
      allowedObjectTypes: ["character", "user"],
    },
    updatePolicy: {
      mode: "eventDrivenWithReview",
      requireFactEvent: true,
      allowedEventTypes: ["betrayal", "threat", "attack", "insult"],
      maxDeltaPerTurn: 10,
      confidenceThreshold: 0.8,
    },
  },
];

export const DEFAULT_TAVERN_STATUS_RULES: TavernStatusRule[] = [
  {
    id: "damage-to-health",
    label: "伤害降低健康",
    when: { eventType: "damage", targetScope: "character" },
    apply: {
      statusId: "health",
      target: "eventTarget",
      op: "add",
      valueByIntensity: {
        trivial: -1,
        minor: -5,
        moderate: -15,
        major: -30,
        critical: -60,
      },
      clamp: [0, 100],
    },
    safeguards: {
      maxDeltaPerTurn: 30,
      requireExplicitEvidence: true,
      manualReviewAboveDelta: 20,
    },
  },
  {
    id: "threat-to-scene-threat",
    label: "威胁事件提升场景威胁",
    when: { eventType: "threat", targetScope: "scene" },
    apply: {
      statusId: "threat_level",
      target: "eventTarget",
      op: "add",
      valueByIntensity: {
        trivial: 2,
        minor: 5,
        moderate: 15,
        major: 40,
        critical: 70,
      },
      clamp: [0, 100],
    },
    safeguards: {
      maxDeltaPerTurn: 40,
      requireExplicitEvidence: true,
      manualReviewAboveDelta: 20,
    },
  },
  {
    id: "stabilize-to-scene-threat",
    label: "稳定行动降低场景威胁",
    when: { eventType: "stabilize", targetScope: "scene" },
    apply: {
      statusId: "threat_level",
      target: "eventTarget",
      op: "add",
      valueByIntensity: {
        trivial: -2,
        minor: -5,
        moderate: -15,
        major: -35,
        critical: -60,
      },
      clamp: [0, 100],
    },
    safeguards: {
      maxDeltaPerTurn: 35,
      requireExplicitEvidence: true,
      manualReviewAboveDelta: 20,
    },
  },
  {
    id: "healing-to-health",
    label: "治疗恢复健康",
    when: { eventType: "healing", targetScope: "character" },
    apply: {
      statusId: "health",
      target: "eventTarget",
      op: "add",
      valueByIntensity: {
        trivial: 1,
        minor: 5,
        moderate: 15,
        major: 30,
        critical: 60,
      },
      clamp: [0, 100],
    },
  },
  {
    id: "shock-to-san",
    label: "冲击降低理智",
    when: { eventType: "sanityShock", targetScope: "character" },
    apply: {
      statusId: "san",
      target: "eventTarget",
      op: "add",
      valueByIntensity: {
        trivial: -1,
        minor: -2,
        moderate: -5,
        major: -15,
        critical: -30,
      },
      clamp: [0, 100],
    },
    safeguards: {
      maxDeltaPerTurn: 15,
      requireExplicitEvidence: true,
      manualReviewAboveDelta: 10,
    },
  },
  {
    id: "help-to-favorability",
    label: "帮助提升被帮助者好感",
    when: { eventType: "help", targetScope: "relationship" },
    apply: {
      statusId: "favorability",
      target: "relationshipTargetToActor",
      op: "add",
      valueByIntensity: {
        trivial: 1,
        minor: 1,
        moderate: 3,
        major: 5,
        critical: 8,
      },
      clamp: [-100, 100],
    },
    safeguards: {
      maxDeltaPerTurn: 5,
      requireExplicitEvidence: true,
      manualReviewAboveDelta: 3,
    },
  },
  {
    id: "betrayal-to-hostility",
    label: "背叛提升受害者敌对",
    when: { eventType: "betrayal", targetScope: "relationship" },
    apply: {
      statusId: "hostility",
      target: "relationshipTargetToActor",
      op: "add",
      valueByIntensity: {
        minor: 5,
        moderate: 10,
        major: 20,
        critical: 35,
      },
      clamp: [0, 100],
    },
    safeguards: {
      maxDeltaPerTurn: 20,
      requireExplicitEvidence: true,
    },
  },
];

export const DEFAULT_TAVERN_TASK_DEFINITIONS: TavernTaskDefinition[] = [
  {
    id: "stabilize-scene-threat",
    title: "稳定当前局势",
    description: "当场景威胁升高时，需要通过明确行动把局势重新压回可控范围。",
    scope: "scene",
    owner: { type: "scene", sceneId: "current" },
    visibility: "public",
    required: true,
    optional: false,
    repeatable: false,
    lifecycle: {
      initialStatus: "inactive",
      startCondition: {
        status: "threat_level",
        target: { type: "scene" },
        gte: 40,
      },
      completeCondition: {
        status: "threat_level",
        target: { type: "scene" },
        lte: 20,
      },
      failCondition: {
        status: "threat_level",
        target: { type: "scene" },
        gte: 90,
      },
    },
    onComplete: [
      {
        type: "messageInline",
        visibility: "public",
        text: "局势暂时稳定下来，新的选择窗口打开了。",
      },
      {
        type: "replyOptions",
        options: [
          {
            id: "progress-reply-check-party",
            text: "确认每个人的状态。",
            targetCharacterIds: [],
            intent: "inspect",
          },
          {
            id: "progress-reply-press-on",
            text: "趁局势稳定继续推进。",
            targetCharacterIds: [],
            intent: "act",
          },
        ],
      },
    ],
    onFail: [
      {
        type: "messageInline",
        visibility: "public",
        text: "局势已经失控，所有人都能感到危险正在逼近。",
      },
      {
        type: "directorDirective",
        instruction: "下一轮聚焦失控后果和角色反应，不要替用户选择撤退或牺牲。",
      },
    ],
  },
  {
    id: "earn-trust-through-help",
    title: "赢得同伴信任",
    description: "通过两次明确帮助或保护行动，让至少一位同伴建立信任。",
    scope: "personal",
    owner: { type: "user", userId: "user" },
    visibility: "owner",
    required: false,
    optional: true,
    repeatable: false,
    lifecycle: {
      initialStatus: "active",
      completeCondition: {
        factEvent: "help",
        actor: { type: "user", userId: "user" },
        countGte: 2,
      },
      failCondition: {
        factEvent: "betrayal",
        actor: { type: "user", userId: "user" },
        countGte: 1,
      },
    },
    onComplete: [
      {
        type: "messageInline",
        visibility: "owner",
        text: "至少一位同伴开始更愿意相信你的判断。",
      },
    ],
  },
];

export const DEFAULT_TAVERN_SCENE_OUTCOMES: TavernSceneOutcomeDefinition[] = [
  {
    id: "scene-stabilized-success",
    label: "局势已稳定",
    winner: [{ type: "user", userId: "user" }],
    condition: {
      task: "stabilize-scene-threat",
      owner: { type: "scene", sceneId: "current" },
      status: "completed",
    },
    priority: 60,
    exclusive: false,
    endScene: "suggest",
    visibility: "public",
    onAchieved: [
      {
        type: "replyOptions",
        options: [
          {
            id: "progress-reply-end-scene",
            text: "确认这一阶段暂时告一段落。",
            targetCharacterIds: [],
            intent: "act",
          },
        ],
      },
    ],
  },
  {
    id: "scene-overwhelmed-failure",
    label: "局势失控",
    loser: [{ type: "user", userId: "user" }],
    condition: {
      status: "threat_level",
      target: { type: "scene" },
      gte: 90,
    },
    priority: 100,
    exclusive: true,
    endScene: "suggest",
    visibility: "public",
  },
];
