import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import * as Lucide from "lucide-react";

const root = fileURLToPath(new URL("../", import.meta.url));
const output = join(root, "source/src/art");
await mkdir(output, { recursive: true });
const assets = {
  ginger: "ginger-i4",
  cream: "cream-o4",
  slate: "slate-l5",
  lilac: "lilac-i2",
  peach: "peach-l3",
  gray: "gray-i2",
  box: "box-frame",
  closedBox: "closed-box",
};
for (const [key, name] of Object.entries(assets)) {
  const data = await readFile(join(root, "assets", name + ".webp"));
  const source =
    "// Generated by scripts/embed-assets.mjs from the approved ImageGen asset.\nexport default " +
    JSON.stringify("data:image/webp;base64," + data.toString("base64")) +
    ";\n";
  if (Buffer.byteLength(source) > 128 * 1024)
    throw new Error(name + " exceeds workshop source limit");
  await writeFile(join(output, key + ".ts"), source);
}
await writeFile(
  join(root, "source/src/art.ts"),
  Object.keys(assets)
    .map((key) => "import " + key + " from './art/" + key + "';")
    .join("\n") +
    "\nexport const art = { " +
    Object.keys(assets).join(", ") +
    " };\n",
);
const icons = {};
for (const name of [
  "Grid2X2",
  "RotateCcw",
  "RotateCw",
  "Undo2",
  "Lightbulb",
  "ArrowRight",
  "ArrowLeft",
  "LockKeyhole",
  "CircleCheck",
  "X",
  "HelpCircle",
  "MousePointer2",
  "Check",
  "LoaderCircle",
]) {
  const svg = renderToStaticMarkup(
    createElement(Lucide[name], {
      size: 24,
      strokeWidth: 1.75,
      color: "#606681",
      xmlns: "http://www.w3.org/2000/svg",
    }),
  );
  icons[name] =
    "data:image/svg+xml;base64," + Buffer.from(svg).toString("base64");
}
await writeFile(
  join(root, "source/src/icons.ts"),
  "// Lucide icon assets, ISC license. Generated by scripts/embed-assets.mjs.\nexport const icons = " +
    JSON.stringify(icons, null, 2) +
    " as const;\n",
);
