import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { prepareBuiltins } from "./builtins.mjs";

export async function prepareRuntime() {
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const result = await build({
    stdin: {
      contents: `import * as React from 'react';
import * as JSX from 'react/jsx-runtime';
import * as DOM from 'react-dom/client';
import { getApplicationViewClient } from '@mewvis/app-sdk/views';
export const modules = {react: React, 'react/jsx-runtime': JSX, 'react-dom/client': DOM,
  '@mewvis/app-sdk/views': {getApplicationViewClient}};`,
      resolveDir: root,
    },
    bundle: true,
    write: false,
    platform: "browser",
    format: "iife",
    globalName: "__workshopRuntime",
    target: "es2022",
    minify: true,
    define: { "process.env.NODE_ENV": '"production"' },
  });
  const output = join(root, "main/host/generated");
  await mkdir(output, { recursive: true });
  // TypeScript's Node sys probes __filename at import time. This app needs only
  // the pure in-memory transpiler, so build without its filesystem/system adapter.
  await build({
    stdin: {
      contents: "import ts from 'typescript'; export default ts;",
      resolveDir: root,
    },
    outfile: join(output, "compiler.js"),
    bundle: true,
    platform: "node",
    format: "esm",
    define: { process: "undefined" },
    target: "es2022",
    minify: true,
  });
  await writeFile(
    join(output, "compiler.d.ts"),
    "export { default } from 'typescript';\n",
  );
  const theme = await readFile(
    fileURLToPath(import.meta.resolve("design-system/tokens.css")),
    "utf8",
  );
  await writeFile(
    join(output, "theme.ts"),
    `// Generated Mewvis theme defaults.\nexport default ${JSON.stringify(theme)};\n`,
  );
  await writeFile(
    join(output, "runtime.ts"),
    `// Generated by scripts/runtime.mjs.\nexport default ${JSON.stringify(result.outputFiles[0].text)};\n`,
  );
  await prepareBuiltins();
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await prepareRuntime();
