/* Generated by scripts/generate-ui.mjs from ui/slots.js. Do not edit. */

export type UIContribution =
  | {
      id: string;
      slot: "session.status";
      type: "text";
      text: string;
      tone?: "neutral" | "info" | "warning";
    }
  | {
      id: string;
      slot: "session.sidebar";
      type: "sidebar";
      title: string;
      icon: "chart" | "files" | "git-branch" | "activity" | "puzzle" | "info";
      view: UIViewReference;
    };

export interface UIViewReference {
  id: string;
}

export const uiSlotDefinitions: {
  readonly sessionStatus: { readonly key: "session.status"; readonly type: "text"; readonly scope: "session" };
  readonly sessionSidebar: { readonly key: "session.sidebar"; readonly type: "sidebar"; readonly scope: "session" };
};
export const uiSlotTypes: {
  readonly text: { readonly type: "text"; readonly schema: object };
  readonly sidebar: { readonly type: "sidebar"; readonly schema: object };
};
