// @generated by protocol/scripts/generate-bindings.mjs
// Sources: protocol/v1/schema/*.schema.json and protocol/v1/openrpc.json
// Do not edit this file directly.
// Example code that deserializes and serializes the model.
// extern crate serde;
// #[macro_use]
// extern crate serde_derive;
// extern crate serde_json;
//
// use generated_module::AgentRuntimeMessage;
//
// fn main() {
//     let json = r#"{"answer": 42}"#;
//     let model: AgentRuntimeMessage = serde_json::from_str(&json).unwrap();
// }

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Any JSON-RPC message crossing the agent runtime stdio boundary.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentRuntimeMessage {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<Error>,

    pub id: Option<Id>,

    pub jsonrpc: Jsonrpc,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub method: Option<RuntimePingRequest>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub params: Option<AgentRuntimeEvent>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<AgentRuntimeResult>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Error {
    pub code: i64,

    pub data: Option<serde_json::Value>,

    pub message: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Id {
    Integer(i64),

    PurpleString(String),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Jsonrpc {
    #[serde(rename = "2.0")]
    The20,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum RuntimePingRequest {
    #[serde(rename = "agent/approval/answer")]
    AgentApprovalAnswer,

    #[serde(rename = "agent/chat")]
    AgentChat,

    #[serde(rename = "agent/question/answer")]
    AgentQuestionAnswer,

    #[serde(rename = "agent/run")]
    AgentRun,

    #[serde(rename = "agent/tools/list")]
    AgentToolsList,

    #[serde(rename = "collaboration/modes/list")]
    CollaborationModesList,

    #[serde(rename = "collaboration/run")]
    CollaborationRun,

    #[serde(rename = "collaboration/runMode")]
    CollaborationRunMode,

    #[serde(rename = "collaboration/timeline/read")]
    CollaborationTimelineRead,

    #[serde(rename = "runtime/event")]
    RuntimeEvent,

    #[serde(rename = "runtime/models/list")]
    RuntimeModelsList,

    #[serde(rename = "runtime/ping")]
    RuntimePing,

    #[serde(rename = "runtime/result")]
    RuntimeResult,

    #[serde(rename = "runtime/session/debug/read")]
    RuntimeSessionDebugRead,

    #[serde(rename = "runtime/session/read")]
    RuntimeSessionRead,

    #[serde(rename = "runtime/sessions/list")]
    RuntimeSessionsList,

    #[serde(rename = "runtime/shutdown")]
    RuntimeShutdown,

    #[serde(rename = "session/agent/compact")]
    SessionAgentCompact,

    #[serde(rename = "session/agent/rebuild")]
    SessionAgentRebuild,

    #[serde(rename = "session/agent/summarize")]
    SessionAgentSummarize,

    #[serde(rename = "session/message/append")]
    SessionMessageAppend,

    #[serde(rename = "session/message/delete")]
    SessionMessageDelete,

    #[serde(rename = "session/message/edit")]
    SessionMessageEdit,

    #[serde(rename = "session/read")]
    SessionRead,

    #[serde(rename = "session/rebuild")]
    SessionRebuild,

    #[serde(rename = "session/summarize")]
    SessionSummarize,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentRuntimeEvent {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_role_id: Option<String>,

    #[serde(rename = "type")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_runtime_event_type: Option<PurpleType>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_task_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub agents: Option<Vec<CollaborationAgent>>,

    /// The user's answer, or null when the user cancels answering.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub answer: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub approval_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub approved: Option<bool>,

    pub args: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub bootstrap_instruction: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub catalog: Option<HashMap<String, RuntimeModelProviderSummary>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub compacted: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    pub context: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_tool_names: Option<Vec<String>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub delta: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_summaries: Option<Vec<RuntimeDisplaySummary>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_summary: Option<RuntimeDisplaySummary>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub event: Option<AgentEvent>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<RuntimeTimelineItem>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub execution_id: Option<String>,

    /// Unix timestamp in milliseconds when this question expires.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_ledger: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_timeline: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_trace: Option<bool>,

    pub input: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_error: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub ledger: Option<Ledger>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_depth: Option<i64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_record_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_record_ids: Option<Vec<String>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub messages: Option<Vec<Message>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub modes: Option<Vec<CollaborationMode>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<HashMap<String, Option<serde_json::Value>>>,

    pub output: Option<serde_json::Value>,

    pub partial_result: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub participants: Option<Vec<CollaborationParticipant>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub permission_options: Option<Vec<AgentPermissionOption>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub permissions: Option<AgentPermissions>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub question: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub question_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub rebuilt: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub record_user_message: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_context: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_contexts: Option<Vec<RuntimeSessionAuxiliaryEntry>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub resources: Option<AgentRuntimeResources>,

    pub result: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub root_dir: Option<String>,

    pub rpc_request_id: Option<JsonRpcId>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime: Option<HashMap<String, Option<serde_json::Value>>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_instruction: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_instructions: Option<Vec<RuntimeSessionAuxiliaryEntry>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_links: Option<Vec<RuntimeLink>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_model: Option<RuntimeModelInput>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_session: Option<RuntimeSessionRef>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub session: Option<RuntimeSessionSummary>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_root_dir: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub sessions: Option<Vec<RuntimeSessionSummary>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub skipped_steps: Option<Vec<CollaborationSkippedStep>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub step: Option<CollaborationS>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub step_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub step_type: Option<StepTypeEnum>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<CollaborationStepResult>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub target: Option<AgentTarget>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeline: Option<Vec<RuntimeTimelineItem>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeline_limit: Option<i64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_name: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<AgentTool>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub trace: Option<Vec<Option<serde_json::Value>>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub trace_limit: Option<i64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_message: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub workflow: Option<Workflow>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub workflow_run_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PurpleType {
    Ack,

    #[serde(rename = "agent_event")]
    AgentEvent,

    #[serde(rename = "agent_tools")]
    AgentTools,

    #[serde(rename = "approval_requested")]
    ApprovalRequested,

    #[serde(rename = "approval_resolved")]
    ApprovalResolved,

    #[serde(rename = "chat_result")]
    ChatResult,

    #[serde(rename = "collaboration_modes_result")]
    CollaborationModesResult,

    #[serde(rename = "collaboration_result")]
    CollaborationResult,

    #[serde(rename = "collaboration_timeline_result")]
    CollaborationTimelineResult,

    Done,

    Error,

    Pong,

    Question,

    #[serde(rename = "question_answered")]
    QuestionAnswered,

    #[serde(rename = "replace_text")]
    ReplaceText,

    #[serde(rename = "runtime_models")]
    RuntimeModels,

    #[serde(rename = "runtime_session_debug_result")]
    RuntimeSessionDebugResult,

    #[serde(rename = "runtime_session_result")]
    RuntimeSessionResult,

    #[serde(rename = "runtime_sessions_result")]
    RuntimeSessionsResult,

    #[serde(rename = "session_mutation_result")]
    SessionMutationResult,

    #[serde(rename = "session_result")]
    SessionResult,

    #[serde(rename = "shutdown_ack")]
    ShutdownAck,

    Started,

    #[serde(rename = "step_done")]
    StepDone,

    #[serde(rename = "step_skipped")]
    StepSkipped,

    #[serde(rename = "step_started")]
    StepStarted,

    #[serde(rename = "task_result")]
    TaskResult,

    #[serde(rename = "text_delta")]
    TextDelta,

    #[serde(rename = "thinking_delta")]
    ThinkingDelta,

    #[serde(rename = "thinking_end")]
    ThinkingEnd,

    #[serde(rename = "tool_call_delta")]
    ToolCallDelta,

    #[serde(rename = "tool_call_end")]
    ToolCallEnd,

    #[serde(rename = "tool_call_start")]
    ToolCallStart,

    #[serde(rename = "tool_execution_end")]
    ToolExecutionEnd,

    #[serde(rename = "tool_execution_start")]
    ToolExecutionStart,

    #[serde(rename = "tool_execution_update")]
    ToolExecutionUpdate,

    #[serde(rename = "workflow_done")]
    WorkflowDone,

    #[serde(rename = "workflow_started")]
    WorkflowStarted,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CollaborationAgent {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub allowed_tools: Option<Vec<String>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled_skills: Option<Vec<String>>,

    pub id: String,

    pub label: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub resources: Option<AgentRuntimeResources>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_model: Option<RuntimeModelInput>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentRuntimeResources {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mcp: Option<AgentRuntimeMcpResources>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub plugins: Option<AgentRuntimePluginResources>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub skills: Option<AgentRuntimeSkillResources>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<AgentRuntimeToolResources>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentRuntimeMcpResources {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub servers: Option<Vec<Option<serde_json::Value>>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentRuntimePluginResources {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<AgentRuntimePlugin>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub settings_path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentRuntimePlugin {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub config: Option<HashMap<String, Option<serde_json::Value>>>,

    pub entry: String,

    pub id: String,

    pub kind: AgentRuntimePluginKind,

    pub package_root: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub patch_path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentRuntimePluginKind {
    Dsh,

    Isle,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentRuntimeSkillResources {
    pub bundled_path: Option<BundledPath>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<Vec<String>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub paths: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BundledPath {
    PurpleString(String),

    StringArray(Vec<String>),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentRuntimeToolResources {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub allowed: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeModelInput {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub api_endpoint: Option<String>,

    pub api_format: RuntimeApiFormat,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,

    pub catalog_model_id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_window: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost: Option<RuntimeModelCost>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub headers: Option<HashMap<String, String>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub input: Option<Vec<RuntimeModelInputModality>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<f64>,

    pub model_id: String,

    pub provider: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking_level: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum RuntimeApiFormat {
    #[serde(rename = "anthropic-messages")]
    AnthropicMessages,

    #[serde(rename = "azure-openai-responses")]
    AzureOpenaiResponses,

    #[serde(rename = "google-generative-ai")]
    GoogleGenerativeAi,

    #[serde(rename = "openai-codex-responses")]
    OpenaiCodexResponses,

    #[serde(rename = "openai-completions")]
    OpenaiCompletions,

    #[serde(rename = "openai-responses")]
    OpenaiResponses,

    Openrouter,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeModelCost {
    pub cache_read: f64,

    pub cache_write: f64,

    pub input: f64,

    pub output: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuntimeModelInputModality {
    Image,

    Text,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeModelProviderSummary {
    pub apis: Vec<RuntimeModelCatalogApi>,

    pub models: HashMap<String, RuntimeModelSummary>,

    pub website_url: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeModelCatalogApi {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub api_endpoint: Option<String>,

    pub api_format: RuntimeApiFormat,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeModelSummary {
    pub context_window: f64,

    pub cost: RuntimeModelCost,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub headers: Option<HashMap<String, String>>,

    pub id: String,

    pub input: Vec<RuntimeModelInputModality>,

    pub max_tokens: f64,

    pub name: String,

    pub reasoning: bool,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking: Option<HashMap<String, RuntimeModelThinking>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeModelThinking {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_level: Option<String>,

    pub levels: Vec<RuntimeThinkingOption>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RuntimeThinkingOption {
    pub label: String,

    pub value: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeDisplaySummary {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub chunk_count: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub entry_count: Option<f64>,

    pub generated_at: f64,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub llm_call_count: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_count: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,

    pub record_id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_char_count: Option<f64>,

    pub summary: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary_instruction: Option<String>,

    pub target_leaf_id: String,

    pub timestamp: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentEvent {
    #[serde(rename = "type")]
    pub agent_event_type: AgentEventType,

    /// The user's answer, or null when the user cancels answering.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub answer: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub approval_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub approved: Option<bool>,

    pub args: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub delta: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub execution_id: Option<String>,

    /// Unix timestamp in milliseconds when this question expires.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub input: Option<AskUserInput>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_error: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,

    pub partial_result: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub question: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub question_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,

    pub result: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_session: Option<RuntimeSessionRef>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_name: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentEventType {
    #[serde(rename = "approval_requested")]
    ApprovalRequested,

    #[serde(rename = "approval_resolved")]
    ApprovalResolved,

    Done,

    Error,

    Question,

    #[serde(rename = "question_answered")]
    QuestionAnswered,

    #[serde(rename = "replace_text")]
    ReplaceText,

    Started,

    #[serde(rename = "text_delta")]
    TextDelta,

    #[serde(rename = "thinking_delta")]
    ThinkingDelta,

    #[serde(rename = "thinking_end")]
    ThinkingEnd,

    #[serde(rename = "tool_call_delta")]
    ToolCallDelta,

    #[serde(rename = "tool_call_end")]
    ToolCallEnd,

    #[serde(rename = "tool_call_start")]
    ToolCallStart,

    #[serde(rename = "tool_execution_end")]
    ToolExecutionEnd,

    #[serde(rename = "tool_execution_start")]
    ToolExecutionStart,

    #[serde(rename = "tool_execution_update")]
    ToolExecutionUpdate,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AskUserInput {
    #[serde(rename = "type")]
    pub ask_user_input_type: InputType,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<AskUserOption>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub selected: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InputType {
    Select,

    Text,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AskUserOption {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    pub label: String,

    pub value: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeSessionRef {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assistant_message_record_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_context_record_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_instruction_record_id: Option<String>,

    pub session_root_dir: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_message_record_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeTimelineItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_role_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_task_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,

    pub id: String,

    pub index: i64,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode_id: Option<String>,

    #[serde(rename = "type")]
    pub runtime_timeline_item_type: String,

    pub source: Source,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<EventStatus>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub step_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub step_type: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub workflow_run_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Source {
    Agent,

    Collaboration,

    Runtime,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EventStatus {
    Done,

    Error,

    Skipped,

    Started,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Ledger {
    pub entries: Vec<Option<serde_json::Value>>,

    pub header: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Message {
    pub content: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_record_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, Option<serde_json::Value>>>,

    pub role: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CollaborationMode {
    pub id: String,

    pub label: String,

    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CollaborationParticipant {
    pub id: String,

    pub kind: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentPermissionOption {
    pub description: String,

    pub is_default: bool,

    pub label: String,

    pub mode: AgentPermissionMode,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentPermissionMode {
    Ask,

    Auto,

    Full,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentPermissions {
    pub mode: AgentPermissionMode,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeSessionAuxiliaryEntry {
    pub content: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, Option<serde_json::Value>>>,

    pub record_id: String,

    pub timestamp: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsonRpcId {
    Integer(i64),

    PurpleString(String),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeLink {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_role_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_session_id: Option<String>,

    pub assistant_message_record_ids: Vec<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<f64>,

    pub link_id: String,

    pub message_record_ids: Vec<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_entry_id: Option<String>,

    pub request_context_record_ids: Vec<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub root_user_entry_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub run_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_id: Option<String>,

    pub runtime_instruction_record_ids: Vec<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<RuntimeLinkStatus>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_message_record_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_message_record_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuntimeLinkStatus {
    Done,

    Error,

    Running,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeSessionSummary {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,

    pub entry_count: i64,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub latest_workflow_run_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub leaf_id: Option<String>,

    pub mode_ids: Vec<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,

    pub session_root_dir: String,

    pub trace_count: i64,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,

    pub workflow_ids: Vec<String>,

    pub workflow_run_ids: Vec<String>,

    pub workspace_path: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CollaborationSkippedStep {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub condition: Option<HashMap<String, Option<serde_json::Value>>>,

    pub reason: String,

    pub step_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CollaborationS {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_role_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_task_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub condition: Option<HashMap<String, Option<serde_json::Value>>>,

    pub output: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_key: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub route: Option<String>,

    pub step_id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub step_type: Option<StepTypeEnum>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StepTypeEnum {
    Agent,

    Condition,

    Dispatch,

    Router,

    Transform,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CollaborationStepResult {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_role_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_task_id: Option<String>,

    pub output: Option<serde_json::Value>,

    pub output_key: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub route: Option<String>,

    pub step_id: String,

    pub step_type: StepTypeEnum,

    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentTarget {
    pub agent_role_id: String,

    pub scope: Scope,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Scope {
    Agent,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentTool {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    pub enabled_by_default: bool,

    pub label: String,

    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Workflow {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub execution_mode: Option<ExecutionMode>,

    pub id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_steps: Option<i64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, Option<serde_json::Value>>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<WorkflowStep>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExecutionMode {
    Parallel,

    Serial,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WorkflowStep {
    pub id: String,

    #[serde(rename = "type")]
    pub workflow_step_type: StepTypeEnum,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentRuntimeResult {
    #[serde(rename = "type")]
    pub agent_runtime_result_type: AgentRuntimeResultType,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub catalog: Option<HashMap<String, RuntimeModelProviderSummary>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub compacted: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_tool_names: Option<Vec<String>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_summaries: Option<Vec<RuntimeDisplaySummary>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_summary: Option<RuntimeDisplaySummary>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<RuntimeTimelineItem>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub ledger: Option<Ledger>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_record_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_record_ids: Option<Vec<String>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub messages: Option<Vec<RuntimeSessionMessage>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub modes: Option<Vec<CollaborationMode>>,

    pub output: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub permission_options: Option<Vec<AgentPermissionOption>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub rebuilt: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_contexts: Option<Vec<RuntimeSessionAuxiliaryEntry>>,

    pub rpc_request_id: Option<JsonRpcId>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_instructions: Option<Vec<RuntimeSessionAuxiliaryEntry>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_links: Option<Vec<RuntimeLink>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub session: Option<RuntimeSessionSummary>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_root_dir: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub sessions: Option<Vec<RuntimeSessionSummary>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub skipped_steps: Option<Vec<CollaborationSkippedStep>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<CollaborationStepResult>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeline: Option<Vec<RuntimeTimelineItem>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<AgentTool>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub trace: Option<Vec<Option<serde_json::Value>>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub workflow_run_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentRuntimeResultType {
    Ack,

    #[serde(rename = "agent_tools")]
    AgentTools,

    #[serde(rename = "chat_result")]
    ChatResult,

    #[serde(rename = "collaboration_modes_result")]
    CollaborationModesResult,

    #[serde(rename = "collaboration_result")]
    CollaborationResult,

    #[serde(rename = "collaboration_timeline_result")]
    CollaborationTimelineResult,

    Pong,

    #[serde(rename = "runtime_models")]
    RuntimeModels,

    #[serde(rename = "runtime_session_debug_result")]
    RuntimeSessionDebugResult,

    #[serde(rename = "runtime_session_result")]
    RuntimeSessionResult,

    #[serde(rename = "runtime_sessions_result")]
    RuntimeSessionsResult,

    #[serde(rename = "session_mutation_result")]
    SessionMutationResult,

    #[serde(rename = "session_result")]
    SessionResult,

    #[serde(rename = "shutdown_ack")]
    ShutdownAck,

    #[serde(rename = "task_result")]
    TaskResult,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeSessionMessage {
    pub content: String,

    pub message_record_id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, Option<serde_json::Value>>>,

    pub role: String,

    pub timestamp: f64,
}

pub const AGENT_RUNTIME_PROTOCOL_VERSION: &str = "1.0.0";
pub const AGENT_RUNTIME_JSON_RPC_METHODS: &[&str] = &[
    "runtime/ping",
    "runtime/shutdown",
    "agent/tools/list",
    "runtime/models/list",
    "agent/chat",
    "agent/run",
    "agent/question/answer",
    "session/read",
    "session/agent/compact",
    "session/agent/rebuild",
    "session/summarize",
    "session/agent/summarize",
    "session/message/edit",
    "session/message/delete",
    "session/message/append",
    "session/rebuild",
    "runtime/sessions/list",
    "runtime/session/read",
    "runtime/session/debug/read",
    "collaboration/timeline/read",
    "collaboration/modes/list",
    "collaboration/run",
    "collaboration/runMode",
    "agent/approval/answer",
];
pub const AGENT_RUNTIME_NOTIFICATION_METHODS: &[&str] = &["runtime/event", "runtime/result"];
pub const METHOD_RUNTIME_PING: &str = "runtime/ping";
pub const METHOD_RUNTIME_SHUTDOWN: &str = "runtime/shutdown";
pub const METHOD_AGENT_TOOLS_LIST: &str = "agent/tools/list";
pub const METHOD_RUNTIME_MODELS_LIST: &str = "runtime/models/list";
pub const METHOD_AGENT_CHAT: &str = "agent/chat";
pub const METHOD_AGENT_RUN: &str = "agent/run";
pub const METHOD_AGENT_QUESTION_ANSWER: &str = "agent/question/answer";
pub const METHOD_SESSION_READ: &str = "session/read";
pub const METHOD_SESSION_AGENT_COMPACT: &str = "session/agent/compact";
pub const METHOD_SESSION_AGENT_REBUILD: &str = "session/agent/rebuild";
pub const METHOD_SESSION_SUMMARIZE: &str = "session/summarize";
pub const METHOD_SESSION_AGENT_SUMMARIZE: &str = "session/agent/summarize";
pub const METHOD_SESSION_MESSAGE_EDIT: &str = "session/message/edit";
pub const METHOD_SESSION_MESSAGE_DELETE: &str = "session/message/delete";
pub const METHOD_SESSION_MESSAGE_APPEND: &str = "session/message/append";
pub const METHOD_SESSION_REBUILD: &str = "session/rebuild";
pub const METHOD_RUNTIME_SESSIONS_LIST: &str = "runtime/sessions/list";
pub const METHOD_RUNTIME_SESSION_READ: &str = "runtime/session/read";
pub const METHOD_RUNTIME_SESSION_DEBUG_READ: &str = "runtime/session/debug/read";
pub const METHOD_COLLABORATION_TIMELINE_READ: &str = "collaboration/timeline/read";
pub const METHOD_COLLABORATION_MODES_LIST: &str = "collaboration/modes/list";
pub const METHOD_COLLABORATION_RUN: &str = "collaboration/run";
pub const METHOD_COLLABORATION_RUN_MODE: &str = "collaboration/runMode";
pub const METHOD_AGENT_APPROVAL_ANSWER: &str = "agent/approval/answer";
pub const NOTIFICATION_RUNTIME_EVENT: &str = "runtime/event";
pub const NOTIFICATION_RUNTIME_RESULT: &str = "runtime/result";
pub const EVENT_STARTED: &str = "started";
pub const EVENT_QUESTION: &str = "question";
pub const EVENT_QUESTION_ANSWERED: &str = "question_answered";
pub const EVENT_REPLACE_TEXT: &str = "replace_text";
pub const EVENT_TEXT_DELTA: &str = "text_delta";
pub const EVENT_THINKING_DELTA: &str = "thinking_delta";
pub const EVENT_THINKING_END: &str = "thinking_end";
pub const EVENT_TOOL_CALL_START: &str = "tool_call_start";
pub const EVENT_TOOL_CALL_DELTA: &str = "tool_call_delta";
pub const EVENT_TOOL_CALL_END: &str = "tool_call_end";
pub const EVENT_TOOL_EXECUTION_START: &str = "tool_execution_start";
pub const EVENT_TOOL_EXECUTION_UPDATE: &str = "tool_execution_update";
pub const EVENT_TOOL_EXECUTION_END: &str = "tool_execution_end";
pub const EVENT_DONE: &str = "done";
pub const EVENT_ERROR: &str = "error";
pub const EVENT_WORKFLOW_STARTED: &str = "workflow_started";
pub const EVENT_STEP_STARTED: &str = "step_started";
pub const EVENT_AGENT_EVENT: &str = "agent_event";
pub const EVENT_STEP_DONE: &str = "step_done";
pub const EVENT_STEP_SKIPPED: &str = "step_skipped";
pub const EVENT_WORKFLOW_DONE: &str = "workflow_done";
pub const EVENT_APPROVAL_REQUESTED: &str = "approval_requested";
pub const EVENT_APPROVAL_RESOLVED: &str = "approval_resolved";
pub const RESULT_ACK: &str = "ack";
pub const RESULT_AGENT_TOOLS: &str = "agent_tools";
pub const RESULT_CHAT_RESULT: &str = "chat_result";
pub const RESULT_PONG: &str = "pong";
pub const RESULT_SHUTDOWN_ACK: &str = "shutdown_ack";
pub const RESULT_TASK_RESULT: &str = "task_result";
pub const RESULT_RUNTIME_MODELS: &str = "runtime_models";
pub const RESULT_SESSION_RESULT: &str = "session_result";
pub const RESULT_SESSION_MUTATION_RESULT: &str = "session_mutation_result";
pub const RESULT_COLLABORATION_RESULT: &str = "collaboration_result";
pub const RESULT_COLLABORATION_MODES_RESULT: &str = "collaboration_modes_result";
pub const RESULT_RUNTIME_SESSIONS_RESULT: &str = "runtime_sessions_result";
pub const RESULT_RUNTIME_SESSION_RESULT: &str = "runtime_session_result";
pub const RESULT_RUNTIME_SESSION_DEBUG_RESULT: &str = "runtime_session_debug_result";
pub const RESULT_COLLABORATION_TIMELINE_RESULT: &str = "collaboration_timeline_result";
