// @generated by protocol/scripts/generate-bindings.mjs
// Sources: protocol/v1/schema/*.schema.json and protocol/v1/openrpc.json
// Do not edit this file directly.
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AgentAccessProtocol = AgentAccess | AgentAccessRoots;
/**
 * Omission means no access. all imposes no additional restriction on the host policy.
 */
export type AgentAccessPaths = "all" | AgentAccessPath[];
export type AgentAccessBase = "workspace" | "pluginData" | "home" | "temp";

/**
 * Host-supplied hard access ceiling, independent of approval mode. Omitted capabilities are denied.
 */
export interface AgentAccess {
  filesystem?: AgentFilesystemAccess;
  network?: AgentNetworkAccess;
  process?: AgentProcessAccess;
}
export interface AgentFilesystemAccess {
  read?: AgentAccessPaths;
  /**
   * Omission means no access. all imposes no additional restriction on the host policy.
   */
  write?: "all" | AgentAccessPath[];
}
export interface AgentAccessPath {
  base: AgentAccessBase;
  /**
   * Optional relative path within the host-resolved base. Absolute paths, parent traversal and globs are forbidden.
   */
  path?: string;
}
export interface AgentNetworkAccess {
  hosts?: "all" | string[];
}
export interface AgentProcessAccess {
  execute?: boolean;
}
/**
 * Additional path bases supplied only by the trusted host. The runtime supplies workspace, home and temp itself.
 */
export interface AgentAccessRoots {
  pluginData?: string;
}
