// @generated by protocol/scripts/generate-bindings.mjs
// Sources: protocol/v1/schema/*.schema.json and protocol/v1/openrpc.json
// Do not edit this file directly.
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ModelThinkingProtocol = RuntimeModelThinking;
export type RuntimeThinkingLevel = string;

export interface RuntimeModelThinking {
  levels: RuntimeThinkingOption[];
  defaultLevel?: string | null;
}
export interface RuntimeThinkingOption {
  value: RuntimeThinkingLevel;
  label: string;
}
