import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const skillsRoot = join(root, "main", "host", "authoring", "skills");
const compatibility =
  (await readFile(join(skillsRoot, "runtime.md"), "utf8")).trimEnd() + "\n";
const output = join(root, "main", "host", "generated", "skills.ts");

const walk = async (directory) =>
  (
    await Promise.all(
      (await readdir(directory, { withFileTypes: true }))
        .sort((left, right) => left.name.localeCompare(right.name))
        .map(async (entry) =>
          entry.isDirectory()
            ? walk(join(directory, entry.name))
            : [join(directory, entry.name)],
        ),
    )
  ).flat();

const parseSkill = async (directory) => {
  const source = await readFile(join(directory, "SKILL.md"), "utf8");
  const block = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(source);
  if (!block) throw new Error(`技能 frontmatter 无效：${directory}`);
  const meta = parse(block[1], { maxAliasCount: 20 });
  const { name, description } = meta;
  if (
    typeof name !== "string" ||
    !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name) ||
    name !== basename(directory) ||
    typeof description !== "string" ||
    !description.trim()
  ) {
    throw new Error(`技能名称、目录或描述无效：${directory}`);
  }
  const privateTool = meta.metadata?.["isle-claw"]?.["required-private-tool"];
  if (typeof privateTool !== "string" || !privateTool.trim())
    throw new Error(`技能未声明 required-private-tool：${name}`);
  const body = source.slice(block[0].length).trim();
  // Only explicit inline paths in SKILL.md are dependencies. Natural-language mentions
  // and example paths in upstream reference documents are not executable declarations.
  const references = [...body.matchAll(/`([^`\n]+)`/g)].map(
    (match) => match[1],
  );
  const paths = references.filter((value) =>
    /^(?:references\/|scripts\/|\.\.\/)/.test(value),
  );
  const resources = paths.filter(
    (value) => /\.(?:md|js|json|py)$/.test(value) && !/[{}*|]/.test(value),
  );
  const resourceDirectories = paths
    .filter((value) => /[{}*]/.test(value))
    .map((value) =>
      value.slice(0, value.search(/[{}*]/)).replace(/[^/]*$/, ""),
    );
  const requirement = {
    name,
    tools: [
      ...new Set([
        privateTool,
        "isle_story_skill",
        "isle_story_skill_resource",
      ]),
    ],
    skills: [
      ...new Set(
        references.filter((value) =>
          /^story-assistant(?:-[a-z]+)*$/.test(value),
        ),
      ),
    ],
    resources: [...new Set(resources)],
    resourceDirectories: [...new Set(resourceDirectories)],
    actions: [
      ...new Set(
        [...body.matchAll(/\baction\s*=\s*["']([a-z_]+)["']/g)].map(
          (match) => match[1],
        ),
      ),
    ],
  };
  return {
    definition: { name, description, content: `${compatibility}${body}` },
    requirement,
  };
};

const directories = (await readdir(skillsRoot, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => join(skillsRoot, entry.name))
  .sort();
const skills = await Promise.all(directories.map(parseSkill));
const definitions = skills.map((skill) => skill.definition);
const requirements = skills.map((skill) => skill.requirement);
const resources = {};
for (const file of (await Promise.all(directories.map(walk))).flat()) {
  const key = relative(skillsRoot, file).replaceAll("\\", "/");
  if (key.endsWith("/SKILL.md") || key.includes("/evals/")) continue;
  resources[key] = await readFile(file, "utf8");
}

const generated =
  `// Generated by scripts/generate-skills.mjs. Do not edit by hand.\n` +
  `export const storySkillDefinitions = ${JSON.stringify(definitions, null, 2)} as const;\n` +
  `export const storySkillRequirements = ${JSON.stringify(requirements, null, 2)} as const;\n` +
  `export const storySkillResources: Readonly<Record<string, string>> = ${JSON.stringify(resources, null, 2)};\n`;
await mkdir(dirname(output), { recursive: true });
await writeFile(output, generated, "utf8");
