import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const skillsRoot = join(root, "skills");
const output = join(root, "main", "host", "story-skills.generated.ts");

const walk = async directory => (await Promise.all((await readdir(directory, { withFileTypes: true }))
  .sort((left, right) => left.name.localeCompare(right.name))
  .map(async entry => entry.isDirectory() ? walk(join(directory, entry.name)) : [join(directory, entry.name)]))).flat();

const parseSkill = async directory => {
  const source = await readFile(join(directory, "SKILL.md"), "utf8");
  const boundary = source.indexOf("\n---", 4);
  if (!source.startsWith("---\n") || boundary < 0) throw new Error(`技能 frontmatter 无效：${directory}`);
  const frontmatter = source.slice(4, boundary);
  const name = /^name:\s*(.+)$/m.exec(frontmatter)?.[1]?.trim();
  const folded = /^description:\s*>-\s*\n((?: {2}.*\n?)*)/m.exec(frontmatter)?.[1];
  const plain = /^description:\s*([^\n]+)$/m.exec(frontmatter)?.[1]?.trim();
  const description = folded
    ? folded.split("\n").map(line => line.replace(/^ {2}/, "").trim()).filter(Boolean).join(" ")
    : plain;
  if (!name || !description) throw new Error(`技能名称或描述无效：${directory}`);
  const body = source.slice(boundary + 4).trim();
  const compatibility = [
    "## Isle 内置故事应用运行约定",
    "",
    "本技能运行在 Isle 内置故事应用中。`story` 工具已经实现同版本 Story Contract；每次调用都必须带上系统提示给出的当前 `workspaceId`。不得猜测或访问其他工作区。",
    "技能提到的 `references/...`、`scripts/...` 或 `../story-assistant/...` 资源由应用私有打包。需要读取时调用 `isle_story_skill_resource`，参数 `skillName` 使用当前技能名，`path` 使用文中相对路径；不要用普通 `read`、`find`、`grep` 或 shell 读取这些应用资源。",
    "脚本资源用于说明确定性检查规则；当前应用不开放进程执行。需要质量检查时读取对应脚本规则并在当前文本上逐项检查，不得声称实际执行了脚本。",
    "技能中的 `ask_user` 表示直接在当前聊天中向用户提出一个简短问题；它不是可调用工具。已有信息足够时直接继续，不要重复确认。",
    "文中出现的 Mewvis 故事弹窗均指当前 Isle 故事助手。",
    "",
  ].join("\n");
  return { name, description, content: `${compatibility}${body}` };
};

const directories = (await readdir(skillsRoot, { withFileTypes: true }))
  .filter(entry => entry.isDirectory())
  .map(entry => join(skillsRoot, entry.name))
  .sort();
const definitions = await Promise.all(directories.map(parseSkill));
const resources = {};
for (const file of await walk(skillsRoot)) {
  const key = relative(skillsRoot, file).replaceAll("\\", "/");
  if (key.endsWith("/SKILL.md") || key.includes("/evals/")) continue;
  resources[key] = await readFile(file, "utf8");
}

const generated = `// Generated by scripts/generate-skills.mjs. Do not edit by hand.\n` +
  `export const storySkillDefinitions = ${JSON.stringify(definitions, null, 2)} as const;\n` +
  `export const storySkillResources: Readonly<Record<string, string>> = ${JSON.stringify(resources, null, 2)};\n`;
await writeFile(output, generated, "utf8");
